export type Article = {
  id: string;
  title: string;
  category: string;
  date: string;
  summary: string;
  emoji: string;
  readTime: string;
  photo: string;
  content: string[];
};

const PH = (seed: string) => `https://picsum.photos/seed/${seed}/800/500`;

export const articles: Article[] = [
  {
    id: "a1",
    title: "5 Cara Mengajarkan Anak Mengelola Emosi",
    category: "Parenting",
    date: "28 Apr 2026",
    summary: "Kecerdasan emosional adalah salah satu bekal terpenting bagi anak. Temukan lima pendekatan praktis yang bisa diterapkan setiap hari di rumah untuk membantu si kecil mengenali dan mengelola perasaannya dengan sehat.",
    emoji: "🧠",
    readTime: "4 menit",
    photo: PH("child-emotions-parenting"),
    content: [
      "Kecerdasan emosional — kemampuan mengenali, memahami, dan mengelola emosi diri sendiri maupun orang lain — terbukti menjadi prediktor kesuksesan yang lebih kuat dibanding IQ. Namun, keterampilan ini tidak datang begitu saja. Ia harus dilatih sejak dini, dan rumah adalah tempat terbaik untuk memulainya.",
      "Pertama, beri nama pada setiap emosi. Ketika anak marah atau sedih, bantu ia mengidentifikasi perasaannya dengan kata-kata: \"Kayaknya kamu lagi kesal ya, karena mainannya diambil?\" Proses penamaan emosi ini (disebut 'emotion labelling') terbukti secara neurologis menurunkan intensitas respons amigdala — bagian otak yang memproses emosi negatif.",
      "Kedua, validasi perasaannya sebelum memberikan solusi. Orang tua sering kali terburu-buru memperbaiki situasi, padahal anak lebih butuh didengar terlebih dahulu. Coba katakan, \"Wajar kamu sedih, itu memang mengecewakan,\" sebelum menawarkan jalan keluar.",
      "Ketiga, ajarkan teknik menenangkan diri yang sederhana. Napas dalam (tarik 4 hitungan, tahan 4, buang 4) sangat efektif untuk anak usia 5 tahun ke atas. Latih saat suasana tenang agar ia bisa menggunakannya sendiri saat emosi memuncak.",
      "Keempat, jadilah model regulasi emosi. Anak belajar paling banyak dari mengamati orang tuanya. Saat Anda sendiri frustrasi, verbalisasikan prosesnya: \"Papa lagi kesal, tapi papa mau tarik napas dulu sebelum bicara.\" Ini memberikan contoh nyata yang jauh lebih berkesan daripada nasihat apapun.",
      "Kelima, ciptakan ruang aman untuk mengekspresikan emosi. Pastikan anak tahu bahwa semua perasaan — termasuk marah dan takut — boleh dirasakan dan dibicarakan di rumah tanpa dihakimi. Sesi check-in harian yang singkat sebelum tidur, seperti \"Cerita satu hal yang bikin kamu senang hari ini dan satu hal yang bikin kamu tidak nyaman,\" bisa membangun kebiasaan ini secara konsisten.",
    ],
  },
  {
    id: "a2",
    title: "Sekolah Terbaik di Bintaro: Panduan Lengkap 2026",
    category: "Sekolah",
    date: "20 Apr 2026",
    summary: "Mencari sekolah yang tepat di Bintaro bisa terasa membingungkan dengan begitu banyak pilihan. Panduan ini merangkum sekolah-sekolah unggulan dari jenjang TK hingga SMA berdasarkan kurikulum, fasilitas, dan ulasan orang tua.",
    emoji: "🎓",
    readTime: "7 menit",
    photo: PH("school-classroom-kids"),
    content: [
      "Bintaro dan kawasan Tangerang Selatan telah berkembang menjadi salah satu pusat pendidikan terbaik di Jabodetabek. Dengan puluhan pilihan sekolah dari berbagai kurikulum — nasional, Cambridge, IB, hingga sekolah Islam terpadu — orang tua kerap merasa kewalahan dalam menentukan pilihan.",
      "Untuk jenjang TK dan SD, hal utama yang perlu diperhatikan adalah pendekatan pedagogi. Sekolah yang mengedepankan play-based learning dan literasi emosional di usia dini terbukti menghasilkan fondasi belajar yang lebih kuat di jenjang berikutnya. Cari sekolah dengan rasio guru-murid di bawah 1:15 dan program transisi TK-SD yang terstruktur.",
      "Di jenjang SMP dan SMA, kurikulum menjadi faktor pembeda utama. Sekolah berbasis Cambridge atau IB menawarkan pengakuan internasional yang menguntungkan bagi anak yang berencana kuliah ke luar negeri. Sementara sekolah dengan Kurikulum Merdeka yang diimplementasikan secara konsisten memberikan keleluasaan eksplorasi minat dan bakat.",
      "Berdasarkan ulasan orang tua di TangselKids sepanjang 2025–2026, beberapa sekolah yang konsisten mendapat penilaian tinggi di Bintaro antara lain: sekolah-sekolah di kawasan Bintaro Jaya Sektor 7 dan 9 yang menawarkan fasilitas lengkap, serta beberapa sekolah Islam terpadu di Pondok Aren yang unggul dalam pembentukan karakter.",
      "Satu tip praktis: kunjungi sekolah pada hari biasa (bukan open house) untuk melihat suasana belajar yang sesungguhnya. Perhatikan bagaimana guru berinteraksi dengan murid, kondisi fasilitas bermain, dan apakah murid tampak aktif dan bahagia. Intuisi Anda sebagai orang tua seringkali tepat.",
    ],
  },
  {
    id: "a3",
    title: "Aktivitas Seru Akhir Pekan Bersama Anak di Tangsel",
    category: "Aktivitas",
    date: "15 Apr 2026",
    summary: "Tidak perlu jauh-jauh keluar kota untuk mengisi akhir pekan yang bermakna bersama keluarga. Tangsel punya banyak destinasi dan kegiatan menyenangkan yang cocok untuk semua usia.",
    emoji: "🎉",
    readTime: "5 menit",
    photo: PH("family-weekend-fun"),
    content: [
      "Salah satu kekhawatiran umum orang tua di area Bintaro dan BSD adalah keterbatasan pilihan aktivitas akhir pekan yang terjangkau namun berkualitas. Ternyata, tanpa harus menempuh perjalanan panjang, Tangerang Selatan menyimpan banyak opsi yang seru dan edukatif.",
      "Untuk anak usia balita hingga SD, playground indoor di berbagai mal dan pusat perbelanjaan di kawasan BSD dan Bintaro menawarkan area bermain yang aman dengan berbagai wahana. Beberapa di antaranya bahkan memiliki area khusus bayi dan area kreatif seperti melukis atau merakit.",
      "Bagi keluarga yang ingin bersentuhan dengan alam, beberapa taman kota dan ruang terbuka hijau di Tangsel bisa menjadi destinasi piknik yang menyenangkan. Aktivitas sederhana seperti bermain bola, bersepeda, atau mengamati burung bisa menjadi pengalaman berharga bagi anak-anak yang tumbuh di lingkungan urban.",
      "Jika anak sudah berusia sekolah, workshop kreatif akhir pekan menjadi pilihan yang semakin populer. Dari kelas memasak anak, kelas seni, hingga workshop coding dan robotik — banyak tempat kursus di Tangsel yang membuka kelas akhir pekan dengan durasi 2–3 jam yang terjangkau.",
      "Jangan lupakan mini zoo dan taman edukasi yang tersebar di beberapa titik di Tangsel. Selain menghibur, kunjungan ke tempat-tempat ini merangsang rasa ingin tahu anak tentang alam dan binatang. Banyak yang bisa dilakukan dengan budget di bawah Rp 100.000 per kepala, cocok untuk keluarga muda.",
    ],
  },
  {
    id: "a4",
    title: "Manfaat Kursus Musik untuk Perkembangan Otak Anak",
    category: "Tumbuh Kembang",
    date: "10 Apr 2026",
    summary: "Penelitian membuktikan bahwa belajar musik sejak dini berdampak positif pada kemampuan bahasa, matematika, dan konsentrasi anak.",
    emoji: "🎵",
    readTime: "5 menit",
    photo: PH("kids-music-lesson-piano"),
    content: [
      "Selama beberapa dekade terakhir, neurosains telah mengumpulkan bukti yang semakin kuat: belajar musik tidak hanya mengembangkan kemampuan bermusik anak, tetapi secara harfiah membentuk ulang struktur otaknya. Anak-anak yang belajar musik secara konsisten menunjukkan materi abu-abu yang lebih tebal di area otak yang berhubungan dengan pemrosesan suara, motorik halus, dan fungsi eksekutif.",
      "Manfaat yang paling sering didokumentasikan adalah peningkatan kemampuan membaca dan berbahasa. Melatih telinga untuk mendengar perbedaan nada meningkatkan kepekaan fonologis — kemampuan yang sama dibutuhkan saat anak belajar membedakan bunyi huruf dan kata. Anak-anak yang kursus musik cenderung lebih cepat membaca dan memiliki kosakata yang lebih kaya.",
      "Hubungan musik dan matematika juga bukan sekadar mitos. Membaca not musik melibatkan pemahaman pecahan (nilai not), pola (ketukan), dan keteraturan (tangga nada) yang secara langsung melatih kemampuan berpikir matematis.",
      "Dari sisi sosial-emosional, berlatih dalam kelompok atau ensemble mengajarkan anak untuk mendengarkan orang lain, menyesuaikan diri, dan berkontribusi pada sesuatu yang lebih besar dari diri sendiri. Konser dan recital, meskipun menegangkan, membangun keberanian tampil yang sangat berharga.",
      "Usia ideal untuk mulai kursus musik adalah 4–6 tahun untuk instrumen seperti piano dan biola yang mengembangkan koordinasi motorik halus. Namun, tidak ada kata terlambat — anak usia 8–10 tahun juga sangat responsif terhadap pembelajaran musik dan seringkali menunjukkan progres yang lebih cepat karena kapasitas kognitif yang lebih matang.",
    ],
  },
  {
    id: "a5",
    title: "Pilih Daycare yang Tepat: 7 Hal yang Harus Diperhatikan",
    category: "Tips Orang Tua",
    date: "5 Apr 2026",
    summary: "Mempercayakan si kecil kepada daycare adalah keputusan besar. Berikut tujuh kriteria penting yang wajib dicek sebelum mendaftar.",
    emoji: "🏠",
    readTime: "6 menit",
    photo: PH("daycare-toddler-play"),
    content: [
      "Memilih daycare adalah salah satu keputusan terpenting yang akan Anda buat sebagai orang tua bekerja. Anak menghabiskan 8–10 jam per hari di tempat ini — kualitas perawatan dan stimulasi yang mereka terima akan berdampak besar pada perkembangan mereka di usia emas ini.",
      "Pertama, perhatikan rasio pengasuh terhadap anak. Untuk bayi (0–1 tahun), standar ideal adalah 1:3 atau maksimal 1:4. Untuk toddler (1–2 tahun), 1:4 hingga 1:5. Semakin kecil rasionya, semakin banyak perhatian individual yang bisa diberikan pada anak Anda.",
      "Kedua, periksa kualifikasi dan turnover pengasuh. Pengasuh yang terlatih dalam perkembangan anak dan P3K adalah nilai tambah besar. Tingkat pergantian staf yang rendah menunjukkan lingkungan kerja yang sehat — dan artinya anak Anda tidak harus terus-menerus beradaptasi dengan wajah baru.",
      "Ketiga, evaluasi keamanan fisik lingkungan. Lantai anti-selip, penutup stop kontak, pagar pengaman tangga, area tidur yang terpisah dari area bermain, dan sistem check-in/check-out yang ketat adalah standar minimum yang tidak boleh ditawar.",
      "Keempat, tanyakan tentang program harian. Daycare berkualitas memiliki jadwal terstruktur yang menyeimbangkan waktu bermain bebas, aktivitas terstruktur, waktu makan, dan tidur siang. Anak-anak, bahkan bayi sekalipun, berkembang lebih baik dalam rutinitas yang dapat diprediksi.",
      "Kelima, cek kebijakan sakit dan komunikasi dengan orang tua. Daycare yang baik memiliki SOP yang jelas soal kapan anak harus dibawa pulang, bagaimana mereka mengkomunikasikan insiden kecil, dan seberapa sering mereka memberikan update harian kepada orang tua — idealnya melalui aplikasi atau grup WhatsApp.",
      "Keenam dan ketujuh: kepercayaan instingtual Anda dan kesehatan anak secara keseluruhan setelah beberapa minggu di daycare. Anak yang senang pergi ke daycare, tidur nyenyak, dan jarang sakit adalah indikator terbaik bahwa Anda telah membuat pilihan yang tepat.",
    ],
  },
  {
    id: "a6",
    title: "Kurikulum Merdeka: Apa yang Perlu Orang Tua Ketahui",
    category: "Pendidikan",
    date: "1 Apr 2026",
    summary: "Kurikulum Merdeka kini diterapkan di hampir seluruh sekolah negeri dan banyak sekolah swasta di Indonesia. Pahami prinsip-prinsipnya dan bagaimana orang tua bisa mendukung anak di rumah.",
    emoji: "📚",
    readTime: "6 menit",
    photo: PH("students-learning-classroom"),
    content: [
      "Kurikulum Merdeka adalah respons pemerintah terhadap berbagai tantangan pendidikan yang terekspos selama pandemi COVID-19: learning loss, kurikulum yang terlalu padat, dan pendekatan pembelajaran yang terlalu berorientasi pada hafalan dan nilai ujian.",
      "Prinsip utama Kurikulum Merdeka adalah 'pembelajaran berdiferensiasi' — guru diharapkan menyesuaikan metode dan materi dengan gaya belajar serta kecepatan masing-masing murid, alih-alih mengajar dengan satu pendekatan untuk semua. Ini adalah pergeseran paradigma yang signifikan dari kurikulum sebelumnya.",
      "Salah satu elemen paling menonjol adalah Proyek Penguatan Profil Pelajar Pancasila (P5), di mana siswa mengerjakan proyek lintas mata pelajaran yang berakar pada isu-isu nyata di lingkungan sekitar mereka. Bagi banyak siswa, ini adalah pertama kalinya mereka belajar memecahkan masalah dunia nyata secara kolaboratif.",
      "Bagi orang tua, ada beberapa implikasi praktis. Pertama, rapor tidak lagi berisi angka semata, melainkan deskripsi naratif tentang perkembangan anak. Beberapa orang tua merasa ini kurang konkret, namun tujuannya adalah memberikan gambaran holistik yang lebih akurat. Kedua, ekspektasi PR dan ujian bisa berbeda signifikan antarsekolah karena keleluasaan implementasi yang diberikan kepada masing-masing satuan pendidikan.",
      "Yang paling bisa Anda lakukan sebagai orang tua adalah membangun komunikasi aktif dengan guru, mendukung anak dalam proyek-proyeknya (bukan mengerjakannya), dan membantu anak mengembangkan rasa ingin tahu serta kemampuan belajar mandiri — dua keterampilan yang menjadi inti dari semangat Kurikulum Merdeka.",
    ],
  },
  {
    id: "a7",
    title: "Playground Indoor vs Outdoor: Mana yang Lebih Baik?",
    category: "Aktivitas",
    date: "25 Mar 2026",
    summary: "Keduanya punya kelebihan dan kekurangan masing-masing. Kami membandingkan manfaat stimulasi fisik dan kognitif dari playground indoor dan outdoor.",
    emoji: "🛝",
    readTime: "4 menit",
    photo: PH("kids-playground-outdoor"),
    content: [
      "Perdebatan playground indoor vs outdoor seringkali diasumsikan memiliki jawaban yang jelas — tentu udara segar dan alam lebih baik, bukan? Namun kenyataannya, kedua jenis playground menawarkan manfaat yang berbeda dan saling melengkapi, bukan saling menggantikan.",
      "Playground outdoor unggul dalam stimulasi fisik yang tidak terbatas. Berlari di permukaan yang tidak rata, memanjat pohon atau batu alam, menggali tanah, dan berinteraksi langsung dengan elemen alam melatih propriosepsi (kesadaran tubuh dalam ruang) dan keberanian mengambil risiko terkalkulasi — dua aspek perkembangan yang sulit direplikasi di dalam ruangan.",
      "Penelitian konsisten menunjukkan bahwa paparan cahaya matahari dan alam mengurangi gejala ADHD, menurunkan tingkat stres, dan meningkatkan kreativitas. Anak-anak yang bermain di luar secara regular juga menunjukkan tingkat kebugaran fisik dan kualitas tidur yang lebih baik.",
      "Di sisi lain, playground indoor memiliki keunggulan dalam iklim tropis seperti Indonesia. Bermain di siang hari tanpa terpapar terik matahari atau hujan memungkinkan anak tetap aktif sepanjang tahun. Playground indoor juga cenderung memiliki permainan yang lebih terstruktur dan aman untuk usia tertentu, dengan pengawasan yang lebih ketat.",
      "Rekomendasi praktis: usahakan anak mendapat minimal 60 menit aktivitas fisik di luar ruangan setiap hari (atau setidaknya beberapa kali seminggu), dan manfaatkan playground indoor sebagai suplemen — terutama saat cuaca tidak mendukung atau sebagai aktivitas sosial terstruktur bersama teman sebaya.",
    ],
  },
  {
    id: "a8",
    title: "Nutrisi Penting untuk Anak Usia 1–5 Tahun",
    category: "Kesehatan",
    date: "18 Mar 2026",
    summary: "Masa emas pertumbuhan anak ada di periode 1–5 tahun. Dokter anak menjelaskan nutrisi-nutrisi kunci yang tidak boleh terlewat dan cara kreatif menyajikannya.",
    emoji: "🥦",
    readTime: "5 menit",
    photo: PH("healthy-food-children"),
    content: [
      "Usia 1–5 tahun adalah periode pertumbuhan otak dan fisik yang paling pesat dalam kehidupan manusia. Selama masa ini, asupan nutrisi yang tepat bukan hanya mendukung pertumbuhan tubuh, tetapi secara harfiah membentuk arsitektur otak yang akan digunakan anak seumur hidupnya.",
      "Zat besi adalah nutrisi nomor satu yang sering terlewat pada anak usia ini. Defisiensi zat besi — bahkan yang ringan sekalipun — berdampak pada kemampuan konsentrasi, memori, dan perkembangan kognitif. Sumber terbaik: daging merah, hati ayam, ikan, dan kacang-kacangan. Pasangkan dengan vitamin C untuk meningkatkan penyerapan.",
      "Omega-3 (terutama DHA) adalah building block utama otak dan retina mata. Anak yang mendapat cukup omega-3 menunjukkan perkembangan bahasa dan kemampuan membaca yang lebih baik. Ikan berlemak seperti salmon dan sarden adalah sumber terbaik — targetkan 2 porsi per minggu.",
      "Zinc sering dilupakan namun krusial untuk pertumbuhan sel, fungsi imun, dan perkembangan kognitif. Kekurangan zinc berdampak pada nafsu makan yang buruk dan pertumbuhan yang terhambat. Sumber terbaik: daging merah, unggas, kacang-kacangan, dan biji-bijian.",
      "Untuk anak yang sulit makan sayur, pendekatan yang terbukti efektif adalah 'food exposure' berulang — penelitian menunjukkan anak perlu terpapar makanan baru 8–15 kali sebelum menerimanya. Jangan menyerah setelah satu atau dua kali penolakan. Libatkan anak dalam proses memasak dan makan bersama sebagai keluarga tanpa tekanan adalah strategi jangka panjang yang paling konsisten berhasil.",
    ],
  },
  {
    id: "a9",
    title: "Review: 5 Kolam Renang Terbaik untuk Anak di BSD",
    category: "Review",
    date: "10 Mar 2026",
    summary: "Tim TangselKids mengunjungi dan menguji langsung lima kolam renang anak di area BSD. Kami nilai dari sisi keamanan, kebersihan, kedalaman kolam, fasilitas, dan keseruan.",
    emoji: "🏊",
    readTime: "6 menit",
    photo: PH("kids-swimming-pool"),
    content: [
      "Bagi keluarga yang tinggal di kawasan BSD dan sekitarnya, kolam renang bukan hanya fasilitas olahraga — ini adalah destinasi rekreasi mingguan yang wajib punya dalam daftar. Tim TangselKids menghabiskan empat akhir pekan untuk mengunjungi dan mengevaluasi lima kolam renang terbaik di area BSD secara langsung.",
      "Kolam pertama yang kami kunjungi unggul dalam hal keamanan: penjaga kolam berlisensi ditempatkan di setiap sudut, kedalaman kolam anak maksimal 60 cm dengan transisi gradual, dan pagar pembatas yang kokoh memisahkan area anak dari kolam dewasa. Airnya jernih dengan kadar klorin yang terasa nyaman — tidak menyengat mata.",
      "Dari sisi fasilitas pendukung, kolam renang terbaik yang kami temui memiliki ruang ganti yang bersih dan luas dengan loker terpisah untuk anak, area menyusui, kantin yang menjual camilan sehat, dan area berteduh yang memadai agar orang tua tidak kepanasan saat menunggu.",
      "Yang membedakan kolam renang yang benar-benar 'family-friendly' dari yang sekadar mengklaim dirinya demikian adalah ketersediaan wahana anak yang beragam: perosotan air, ember tumpah, jet air untuk diinjak, dan kolam arus kecil yang memungkinkan anak bermain air dengan cara yang lebih variatif dari sekadar berenang.",
      "Dari sisi harga, rentang tiket masuk di area BSD berkisar Rp 25.000 hingga Rp 75.000 per orang untuk hari kerja, dengan surcharge akhir pekan yang bervariasi. Beberapa kolam menawarkan membership bulanan atau tahunan yang jauh lebih ekonomis bagi keluarga yang rutin datang. Cek halaman masing-masing tempat di TangselKids untuk detail harga terkini.",
    ],
  },
  {
    id: "a10",
    title: "Cara Mendampingi Anak Belajar di Rumah",
    category: "Parenting",
    date: "3 Mar 2026",
    summary: "Dengan pendekatan yang tepat, waktu belajar bisa menjadi momen bonding yang menyenangkan sekaligus membangun kebiasaan belajar mandiri yang akan bertahan seumur hidup.",
    emoji: "📝",
    readTime: "5 menit",
    photo: PH("parent-child-studying"),
    content: [
      "Mendampingi anak belajar adalah salah satu tanggung jawab orang tua yang terasa simpel di permukaan namun penuh nuansa dalam praktiknya. Bagaimana Anda hadir saat anak belajar — seberapa banyak bantuan yang diberikan, nada suara yang digunakan, reaksi terhadap kesalahan — semua ini membentuk hubungan anak dengan belajar itu sendiri.",
      "Prinsip terpenting: tujuan Anda bukan memastikan PR selesai dengan benar, melainkan membangun kepercayaan diri dan kemandirian belajar. Ini berarti menahan godaan untuk langsung memberikan jawaban ketika anak buntu. Alih-alih, ajukan pertanyaan pemandu: 'Menurutmu, kita mulai dari mana dulu?' atau 'Bagian mana yang sudah kamu mengerti?'",
      "Ciptakan lingkungan fisik yang kondusif. Meja belajar yang teratur, pencahayaan yang cukup, dan minimnya gangguan (ponsel, TV) berkontribusi signifikan pada kemampuan konsentrasi. Penelitian menunjukkan bahwa bahkan keberadaan ponsel di atas meja — meski dalam kondisi mati — menurunkan kapasitas kognitif yang tersedia untuk belajar.",
      "Jadwalkan sesi belajar pada waktu yang konsisten setiap hari. Otak anak (dan orang dewasa) bekerja paling baik dengan rutinitas yang dapat diprediksi. Mulai dengan sesi pendek (20–30 menit) diselingi istirahat aktif, dan secara bertahap tingkatkan durasinya sesuai usia dan kemampuan konsentrasi anak.",
      "Terakhir, rayakan proses, bukan hanya hasil. Pujian yang spesifik pada usaha ('Kamu mau coba berkali-kali sampai berhasil — itu yang bikin kamu berkembang') jauh lebih memotivasi dibanding pujian pada kecerdasan ('Kamu memang pintar'). Ini bukan sekadar kata-kata — penelitian Carol Dweck selama 30 tahun membuktikan bahwa growth mindset yang dibentuk sejak kecil adalah salah satu penentu terbesar kesuksesan jangka panjang.",
    ],
  },
];
