export type Grade = "Preschool" | "TK" | "SD" | "SMP" | "SMA";

export type Review = {
  name: string;
  rating: number;
  comment: string;
  date: string;
};

export type TangselKidsRating = {
  cleanliness: number;
  value: number;
  safety: number;
  fun: number;
  facilities: number;
  verdict: string;
};

export type Place = {
  id: string;
  category: "school" | "learning-center" | "daycare" | "playground" | "clinic" | "cafe" | "mini-zoo" | "swimming-pool" | "bookstore";
  name: string;
  area: string;
  address?: string;
  curriculum?: string;
  grades?: Grade[];
  centerType?: string;
  playgroundType?: "indoor" | "outdoor";
  isFree?: boolean;
  priceMin: number;
  priceMax: number;
  rating: number;
  reviews: number;
  ageRange: string;
  hours: string;
  description: string;
  phone: string;
  tag?: string;
  isFeatured?: boolean;
  icon: string;
  photo: string;
  photos?: string[];
  reviewsList?: Review[];
  tangselKidsRating?: TangselKidsRating;
  instagram?: string;
  facebook?: string;
  tiktok?: string;
  website?: string;

  // ── School-specific ─────────────────────────────────────────
  uangPangkalMin?: number;   // one-time enrollment / admission fee (min)
  uangPangkalMax?: number;   // one-time enrollment / admission fee (max)
  bahasa?: string[];         // ["Indonesia", "English", "Bilingual", "Arabic"]

  // ── Learning-center-specific ─────────────────────────────────
  courseTypes?: string[];    // multi-valued, e.g. ["English", "Math"]
  ageGroups?: string[];      // ["Toddler", "Kids", "Tween", "Teen"]

  // ── Daycare-specific ─────────────────────────────────────────
  careHours?: "full-day" | "half-day";
  daycareFeatures?: string[]; // ["CCTV", "Meals", "WhatsApp Report", ...]
  daycareAgeGroups?: string[]; // ["Bayi (0–1 thn)", "Toddler (1–2 thn)", "Balita (2–4 thn)", "Usia 4+ thn"]

  // ── Clinic-specific ──────────────────────────────────────────
  clinicServices?: string[]; // ["Terapi Wicara", "Terapi Fisik", "Terapi Occupasi", ...]
  bpjs?: boolean;

  // ── Cafe-specific ────────────────────────────────────────────
  cafeFeatures?: string[];   // ["Playground Indoor", "Playground Outdoor", "Area Mewarnai", ...]
  priceCategory?: string; // "Murah Sekali" | "Murah" | "Normal" | "Agak Mahal" | "Mahal"

  // ── Swimming-pool-specific ───────────────────────────────────
  poolFeatures?: string[];   // ["Kolam Anak", "Baby Swim", "Kelas Renang", "Indoor", "Loker", "Kantin"]

  // ── Bookstore-specific ───────────────────────────────────────
  bookCollection?: string[]; // ["Buku Indonesia", "Buku Inggris", "Buku Import", "Stationery"]
};

/** Returns which area group a place belongs to. */
export function getAreaGroup(area: string): "bintaro" | "bsd" | "both" {
  const a = area.toLowerCase();
  if (a.includes("bsd")) return "bsd";
  if (a.includes("tangsel") || a.includes("tangerang selatan")) return "both";
  return "bintaro";
}

/**
 * Returns true if the place matches at least one of the selected area groups.
 * Pass an empty array (or ["all"]) to match everything.
 * Places whose getAreaGroup() === "both" always match any selection.
 */
export function placeMatchesAreas(place: Place, selectedAreas: string[]): boolean {
  if (selectedAreas.length === 0 || selectedAreas.includes("all")) return true;
  const group = getAreaGroup(place.area);
  if (group === "both") return true;
  return selectedAreas.includes(group);
}

export function formatPrice(price: number): string {
  if (price === 0) return "Gratis";
  if (price >= 1000000) {
    const val = price / 1000000;
    return val % 1 === 0 ? `${val}jt` : `${val.toFixed(1)}jt`;
  }
  return `${(price / 1000).toFixed(0)}k`;
}

export function formatPriceRange(min: number, max: number): string {
  if (min === 0 && max === 0) return "Gratis";
  return `Rp ${formatPrice(min)} – ${formatPrice(max)} / bln`;
}

const PH = (seed: string) => `https://picsum.photos/seed/${seed}/800/500`;

export const places: Place[] = [
  // ── SCHOOLS ──────────────────────────────────────────────
  {
    id: "s1",
    category: "school",
    isFeatured: true,
    name: "Little Stars Montessori",
    area: "Bintaro Sektor 7",
    address: "Jl. Bintaro Utama VII No. 15, Sektor 7, Pesanggrahan, Jakarta Selatan",
    curriculum: "Montessori",
    grades: ["TK"],
    priceMin: 2500000,
    priceMax: 4000000,
    uangPangkalMin: 5000000,
    uangPangkalMax: 10000000,
    bahasa: ["Bilingual (ID+EN)"],
    rating: 4.9,
    reviews: 42,
    ageRange: "2 – 6 tahun",
    hours: "07:30 – 14:00",
    description: "Little Stars Montessori menyediakan lingkungan belajar yang hangat dan berbasis alam untuk anak usia dini. Dengan metode Montessori yang terbukti, anak-anak belajar mandiri, kreatif, dan percaya diri.",
    phone: "0812-3456-7890",
    tag: "Top Rated",
    icon: "🏫",
    photo: PH("classroom-bright"),
    photos: [PH("montessori-kids"), PH("school-garden")],
    instagram: "https://instagram.com/example",
    facebook: "https://facebook.com/example",
    tiktok: "https://tiktok.com/@example",
    website: "https://example.com",
    reviewsList: [
      { name: "Dewi K.", rating: 5, comment: "Guru-gurunya sangat sabar dan perhatian. Anak saya berkembang pesat sejak masuk sini!", date: "Mar 2025" },
      { name: "Budi S.", rating: 5, comment: "Lingkungan sekolah bersih dan nyaman. Metode Montessori benar-benar terasa bedanya.", date: "Feb 2025" },
      { name: "Rina A.", rating: 5, comment: "Anak kami jadi lebih mandiri dan percaya diri. Sangat puas!", date: "Jan 2025" },
    ],
  },
  {
    id: "s2",
    category: "school",
    name: "Global Kids International",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Raya No. 42, Bintaro, Pesanggrahan, Jakarta Selatan",
    curriculum: "Cambridge",
    grades: ["TK", "SD"],
    priceMin: 5000000,
    priceMax: 8000000,
    uangPangkalMin: 20000000,
    uangPangkalMax: 35000000,
    bahasa: ["English", "Bilingual (ID+EN)"],
    rating: 4.7,
    reviews: 31,
    ageRange: "3 – 12 tahun",
    hours: "07:00 – 15:00",
    description: "Sekolah internasional dengan kurikulum Cambridge yang mengembangkan kemampuan bilingual sejak dini. Fasilitas lengkap dan tenaga pengajar berpengalaman internasional.",
    phone: "0812-9876-5432",
    tag: "International",
    icon: "🏫",
    photo: PH("school-building-modern"),
    photos: [PH("international-classroom"), PH("school-library")],
    reviewsList: [
      { name: "Maya H.", rating: 5, comment: "Fasilitas kelas dunia, guru native speaker. Worth the price!", date: "Mar 2025" },
      { name: "Ahmad F.", rating: 4, comment: "Kurikulum Cambridge sangat bagus. Anak jadi fasih bahasa Inggris.", date: "Jan 2025" },
    ],
  },
  {
    id: "s3",
    category: "school",
    name: "Al-Azhar Islamic School",
    area: "Bintaro",
    address: "Jl. Al Azhar No. 3, Bintaro, Pesanggrahan, Jakarta Selatan",
    curriculum: "Islam Terpadu",
    grades: ["TK"],
    priceMin: 1500000,
    priceMax: 2500000,
    uangPangkalMin: 3000000,
    uangPangkalMax: 7000000,
    bahasa: ["Bilingual (ID+ARB)"],
    rating: 4.8,
    reviews: 56,
    ageRange: "4 – 6 tahun",
    hours: "07:00 – 12:00",
    description: "Sekolah Islam terpadu yang mengintegrasikan pendidikan umum dengan nilai-nilai Islami. Program hafalan Al-Quran dan bahasa Arab tersedia untuk semua jenjang.",
    phone: "0813-2345-6789",
    tag: "Most Loved",
    icon: "🏫",
    photo: PH("islamic-school"),
    photos: [PH("quran-learning"), PH("islamic-classroom")],
    reviewsList: [
      { name: "Siti R.", rating: 5, comment: "Program quran-nya luar biasa. Anak saya sudah hafal 5 juz di usia 6 tahun!", date: "Feb 2025" },
      { name: "Hendra W.", rating: 5, comment: "Gurunya ramah, pendidikan agama dan umum seimbang banget.", date: "Jan 2025" },
    ],
  },
  {
    id: "s4",
    category: "school",
    name: "Sekolah Alam Tangsel",
    area: "Pesanggrahan",
    address: "Jl. Pondok Betung No. 7, Pesanggrahan, Tangerang Selatan",
    curriculum: "Merdeka",
    grades: ["TK"],
    priceMin: 1000000,
    priceMax: 2000000,
    uangPangkalMin: 2000000,
    uangPangkalMax: 5000000,
    bahasa: ["Indonesian"],
    rating: 4.6,
    reviews: 28,
    ageRange: "3 – 6 tahun",
    hours: "07:30 – 13:00",
    description: "Sekolah berbasis alam yang mengajak anak belajar langsung dari lingkungan. Metode menyenangkan dengan aktivitas luar ruang setiap hari dan kebun sekolah.",
    phone: "0814-3456-7891",
    icon: "🏫",
    photo: PH("nature-school-outdoor"),
    photos: [PH("kids-garden-play"), PH("outdoor-learning")],
    reviewsList: [
      { name: "Fitri L.", rating: 5, comment: "Konsep belajar di alam sangat cocok untuk anak yang aktif. Anak kami jadi lebih suka eksplorasi.", date: "Mar 2025" },
      { name: "Agus P.", rating: 4, comment: "Unik dan menyenangkan. Berbeda dari sekolah konvensional.", date: "Feb 2025" },
    ],
  },
  {
    id: "s5",
    category: "school",
    name: "Kinderland Preschool",
    area: "Bintaro Sektor 1",
    address: "Jl. RC Veteran No. 10, Sektor 1, Bintaro, Jakarta Selatan",
    curriculum: "Nasional Plus",
    grades: ["TK"],
    priceMin: 2000000,
    priceMax: 3500000,
    uangPangkalMin: 5000000,
    uangPangkalMax: 10000000,
    bahasa: ["Bilingual (ID+EN)"],
    rating: 4.7,
    reviews: 38,
    ageRange: "2 – 5 tahun",
    hours: "08:00 – 13:00",
    description: "Prasekolah bilingual yang menyeimbangkan pembelajaran bahasa Inggris dan Indonesia. Program seni, musik, dan olahraga terintegrasi dalam kurikulum harian.",
    phone: "0815-4567-8902",
    icon: "🏫",
    photo: PH("preschool-colorful"),
    photos: [PH("preschool-music"), PH("kids-art-class")],
    reviewsList: [
      { name: "Dian M.", rating: 5, comment: "Anak saya sudah bisa bicara Inggris dasar di usia 4 tahun! Guru-gurunya sabar.", date: "Feb 2025" },
      { name: "Rina A.", rating: 4, comment: "Program bilingual-nya efektif. Fasilitas juga bagus.", date: "Jan 2025" },
    ],
  },
  {
    id: "s6",
    category: "school",
    name: "Rainbow Kids School",
    area: "Pondok Jaya",
    address: "Jl. Pondok Jaya Raya No. 22, Pondok Jaya, Tangerang Selatan",
    curriculum: "Nasional Plus",
    grades: ["TK"],
    priceMin: 800000,
    priceMax: 1500000,
    uangPangkalMin: 1000000,
    uangPangkalMax: 3000000,
    bahasa: ["Indonesian"],
    rating: 4.5,
    reviews: 22,
    ageRange: "3 – 6 tahun",
    hours: "07:30 – 11:30",
    description: "Taman kanak-kanak berbasis kurikulum nasional plus dengan pendekatan bermain sambil belajar yang menyenangkan dan biaya terjangkau untuk keluarga Bintaro.",
    phone: "0816-5678-9013",
    tag: "Budget Friendly",
    icon: "🏫",
    photo: PH("kids-school-rainbow"),
    photos: [PH("classroom-colorful"), PH("kids-playing-school")],
    reviewsList: [
      { name: "Budi S.", rating: 5, comment: "Harga terjangkau tapi kualitas bagus. Guru-gurunya berdedikasi.", date: "Mar 2025" },
      { name: "Siti R.", rating: 4, comment: "Pilihan terbaik buat keluarga yang budget-conscious. Anak kami happy banget.", date: "Feb 2025" },
    ],
  },
  {
    id: "s7",
    category: "school",
    name: "SD Harapan Bangsa Bintaro",
    area: "Bintaro Sektor 3",
    address: "Jl. Sektor 3 No. 18, Bintaro Sektor 3, Tangerang Selatan",
    curriculum: "Nasional",
    grades: ["SD"],
    priceMin: 900000,
    priceMax: 1800000,
    uangPangkalMin: 2000000,
    uangPangkalMax: 5000000,
    bahasa: ["Indonesian", "English"],
    rating: 4.6,
    reviews: 44,
    ageRange: "6 – 12 tahun",
    hours: "07:00 – 13:30",
    description: "Sekolah dasar nasional plus dengan program pengembangan karakter dan literasi digital. Lingkungan belajar modern dengan laboratorium komputer dan perpustakaan lengkap.",
    phone: "0828-1234-5670",
    tag: "Nasional",
    icon: "🏫",
    photo: PH("elementary-school-kids"),
    photos: [PH("school-lab-computer"), PH("elementary-classroom")],
    reviewsList: [
      { name: "Ahmad F.", rating: 5, comment: "Program literasi digital-nya keren. Anak saya jadi melek teknologi dari dini.", date: "Mar 2025" },
      { name: "Maya H.", rating: 4, comment: "Gurunya profesional, fasilitas sekolah terus diupgrade.", date: "Jan 2025" },
    ],
  },
  {
    id: "s8",
    category: "school",
    name: "SMP Bintaro Jaya Global",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Bintaro No. 5, Bintaro, Tangerang Selatan",
    curriculum: "Nasional",
    grades: ["SMP"],
    priceMin: 1200000,
    priceMax: 2200000,
    uangPangkalMin: 3000000,
    uangPangkalMax: 8000000,
    bahasa: ["Bilingual (ID+EN)"],
    rating: 4.5,
    reviews: 37,
    ageRange: "12 – 15 tahun",
    hours: "07:00 – 14:30",
    description: "SMP dengan program bilingual dan kegiatan ekstrakurikuler lengkap. Fasilitas laboratorium sains, aula olahraga, dan program pertukaran pelajar internasional.",
    phone: "0829-2345-6781",
    icon: "🏫",
    photo: PH("middle-school-classroom"),
    photos: [PH("school-science-lab"), PH("students-library")],
    reviewsList: [
      { name: "Dewi K.", rating: 5, comment: "Ekskul-nya banyak dan berkualitas. Anak kami menemukan passionnya di sini.", date: "Feb 2025" },
      { name: "Hendra W.", rating: 4, comment: "Lab sains lengkap banget, anak jadi makin suka pelajaran IPA.", date: "Jan 2025" },
    ],
  },
  {
    id: "s9",
    category: "school",
    name: "SMA Dwiwarna BSD",
    area: "BSD City",
    address: "Jl. BSD Raya Utama No. 1, BSD City, Tangerang Selatan",
    curriculum: "Merdeka",
    grades: ["SMA"],
    priceMin: 1500000,
    priceMax: 2800000,
    uangPangkalMin: 5000000,
    uangPangkalMax: 12000000,
    bahasa: ["Indonesian", "English"],
    rating: 4.7,
    reviews: 52,
    ageRange: "15 – 18 tahun",
    hours: "07:00 – 15:00",
    description: "SMA unggulan di BSD dengan jurusan IPA, IPS, dan Bahasa. Tingkat kelulusan 100% dengan banyak alumni diterima di universitas negeri dan luar negeri.",
    phone: "0830-3456-7892",
    tag: "Top Rated",
    icon: "🏫",
    photo: PH("high-school-students"),
    photos: [PH("highschool-campus"), PH("graduation-ceremony")],
    reviewsList: [
      { name: "Fitri L.", rating: 5, comment: "Alumni-nya banyak yang masuk PTN favorit. Guru-guru sangat supportive untuk persiapan kuliah.", date: "Mar 2025" },
      { name: "Agus P.", rating: 5, comment: "Sekolah terbaik di BSD. Anak kami berhasil masuk UI setelah lulus dari sini.", date: "Feb 2025" },
    ],
  },

  {
    id: "s10",
    category: "school",
    name: "Bintaro World School",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Raya No. 88, Bintaro, Tangerang Selatan",
    curriculum: "IB",
    grades: ["TK", "SD", "SMP"],
    priceMin: 7000000,
    priceMax: 12000000,
    uangPangkalMin: 30000000,
    uangPangkalMax: 60000000,
    bahasa: ["English", "Bilingual (ID+EN)"],
    rating: 4.9,
    reviews: 27,
    ageRange: "4 – 15 tahun",
    hours: "07:30 – 15:30",
    description: "Sekolah berstandar International Baccalaureate (IB) dengan pendekatan inquiry-based learning. Murid dipersiapkan untuk melanjutkan pendidikan di universitas terkemuka dunia.",
    phone: "0812-9988-7766",
    tag: "International",
    icon: "🏫",
    photo: PH("ib-school-modern"),
    photos: [PH("ib-classroom"), PH("school-international-campus")],
    reviewsList: [
      { name: "Indira T.", rating: 5, comment: "Kurikulum IB-nya luar biasa, anak sangat terlatih berpikir kritis dan presentasi sejak dini.", date: "Feb 2025" },
      { name: "Reza P.", rating: 5, comment: "Guru-guru berpengalaman internasional. Investasi terbaik untuk masa depan anak.", date: "Jan 2025" },
    ],
  },
  {
    id: "s11",
    category: "school",
    name: "Kreativa Blended School BSD",
    area: "BSD City",
    address: "Jl. BSD Raya Selatan No. 14, BSD City, Tangerang Selatan",
    curriculum: "Blended Learning",
    grades: ["SD", "SMP"],
    priceMin: 1800000,
    priceMax: 3200000,
    uangPangkalMin: 6000000,
    uangPangkalMax: 12000000,
    bahasa: ["Indonesian", "English"],
    rating: 4.6,
    reviews: 33,
    ageRange: "6 – 15 tahun",
    hours: "08:00 – 14:30",
    description: "Sekolah inovatif yang memadukan pembelajaran tatap muka dan digital secara terstruktur. Platform e-learning eksklusif memungkinkan siswa belajar sesuai kecepatan masing-masing.",
    phone: "0821-5544-3322",
    tag: "Inovatif",
    icon: "🏫",
    photo: PH("blended-school-digital"),
    photos: [PH("students-tablet-learning"), PH("classroom-tech-school")],
    reviewsList: [
      { name: "Bagas W.", rating: 5, comment: "Kombinasi offline-online-nya sangat efektif. Anak saya jadi lebih mandiri dalam belajar.", date: "Mar 2025" },
      { name: "Laras K.", rating: 4, comment: "Platform digitalnya user-friendly. Orang tua bisa pantau progress belajar anak setiap hari.", date: "Jan 2025" },
    ],
  },
  {
    id: "s12",
    category: "school",
    name: "Sekolah Karakter Nusantara",
    area: "Pondok Aren",
    address: "Jl. Pondok Aren Indah No. 9, Pondok Aren, Tangerang Selatan",
    curriculum: "Others",
    grades: ["TK", "SD"],
    priceMin: 700000,
    priceMax: 1400000,
    uangPangkalMin: 1500000,
    uangPangkalMax: 4000000,
    bahasa: ["Indonesian"],
    rating: 4.4,
    reviews: 19,
    ageRange: "4 – 12 tahun",
    hours: "07:30 – 13:00",
    description: "Sekolah berbasis pengembangan karakter dengan pendekatan holistik yang menggabungkan kearifan lokal, kesenian, dan nilai-nilai Pancasila dalam setiap kegiatan belajar.",
    phone: "0813-6677-8899",
    icon: "🏫",
    photo: PH("character-school-nusantara"),
    photos: [PH("kids-traditional-arts"), PH("school-culture-day")],
    reviewsList: [
      { name: "Nanda S.", rating: 5, comment: "Sekolah yang benar-benar fokus pada pembentukan karakter. Anak saya jadi lebih sopan dan berempati.", date: "Feb 2025" },
      { name: "Prasetyo A.", rating: 4, comment: "Program kearifan lokal sangat unik. Anak belajar budaya Indonesia sambil tetap mengikuti kurikulum.", date: "Jan 2025" },
    ],
  },

  {
    id: "s13",
    category: "school",
    name: "Mandarin Star School Bintaro",
    area: "Bintaro Sektor 7",
    address: "Jl. Bintaro Utama VII No. 60, Sektor 7, Tangerang Selatan",
    curriculum: "Nasional Plus",
    grades: ["TK", "SD"],
    priceMin: 3000000,
    priceMax: 5500000,
    uangPangkalMin: 10000000,
    uangPangkalMax: 20000000,
    bahasa: ["Bilingual (ID+MND)"],
    rating: 4.7,
    reviews: 24,
    ageRange: "4 – 12 tahun",
    hours: "07:30 – 14:30",
    description: "Sekolah bilingual Indonesia–Mandarin dengan guru native speaker dari Tiongkok. Program intensif bahasa Mandarin sejak TK membangun fondasi literasi yang kuat untuk masa depan global.",
    phone: "0812-7788-9900",
    tag: "Mandarin",
    icon: "🏫",
    photo: PH("mandarin-school-class"),
    photos: [PH("kids-mandarin-learning"), PH("chinese-classroom")],
    reviewsList: [
      { name: "Cindy L.", rating: 5, comment: "Anak saya sudah bisa percakapan dasar Mandarin dalam 6 bulan! Guru native speaker-nya sangat efektif.", date: "Mar 2025" },
      { name: "Kevin T.", rating: 4, comment: "Program Mandarin-nya terstruktur dan menyenangkan. Investasi bahasa yang sangat worth it.", date: "Jan 2025" },
    ],
  },
  {
    id: "s14",
    category: "school",
    name: "Bintaro Japanese School",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Bintaro No. 77, Tangerang Selatan",
    curriculum: "Others",
    grades: ["TK", "SD", "SMP"],
    priceMin: 4000000,
    priceMax: 7000000,
    uangPangkalMin: 15000000,
    uangPangkalMax: 30000000,
    bahasa: ["Japanese"],
    rating: 4.8,
    reviews: 16,
    ageRange: "4 – 15 tahun",
    hours: "08:00 – 15:00",
    description: "Sekolah Jepang resmi di Bintaro mengikuti kurikulum Monbukagakusho. Ditujukan untuk keluarga ekspatriat Jepang maupun anak-anak Indonesia yang ingin fasih berbahasa Jepang.",
    phone: "0812-3344-5566",
    tag: "Japanese",
    icon: "🏫",
    photo: PH("japanese-school-kids"),
    photos: [PH("japanese-classroom"), PH("kids-japanese-culture")],
    reviewsList: [
      { name: "Yuki M.", rating: 5, comment: "Sekolah yang sangat profesional mengikuti standar Jepang. Anak kami nyaman belajar di sini.", date: "Feb 2025" },
      { name: "Hana S.", rating: 5, comment: "Budaya dan disiplin Jepang diajarkan dengan baik. Sangat recommended untuk keluarga Jepang di Tangsel.", date: "Jan 2025" },
    ],
  },
  {
    id: "s15",
    category: "school",
    name: "Deutsche Schule Tangsel",
    area: "BSD City",
    address: "Jl. BSD Raya Utama No. 33, BSD City, Tangerang Selatan",
    curriculum: "Others",
    grades: ["TK", "SD", "SMP", "SMA"],
    priceMin: 5000000,
    priceMax: 9000000,
    uangPangkalMin: 20000000,
    uangPangkalMax: 45000000,
    bahasa: ["German"],
    rating: 4.7,
    reviews: 12,
    ageRange: "4 – 18 tahun",
    hours: "07:30 – 14:00",
    description: "Sekolah Jerman bersertifikat DSD (Deutsches Sprachdiplom) dengan kurikulum Eropa. Lulusan mendapat pengakuan ijazah internasional untuk melanjutkan studi di Jerman dan Eropa.",
    phone: "0812-6655-4433",
    tag: "German",
    icon: "🏫",
    photo: PH("german-school-classroom"),
    photos: [PH("kids-german-learning"), PH("european-school-campus")],
    reviewsList: [
      { name: "Hans B.", rating: 5, comment: "Kurikulum Jerman yang ketat namun sangat berkualitas. Anak kami siap lanjut kuliah di Eropa.", date: "Mar 2025" },
      { name: "Tia R.", rating: 4, comment: "Satu-satunya sekolah Jerman di Tangsel. Pengalaman belajar yang benar-benar internasional.", date: "Feb 2025" },
    ],
  },

  // ── LEARNING CENTERS ─────────────────────────────────────
  {
    id: "lc1",
    category: "learning-center",
    name: "Spark English Center",
    area: "Pondok Jaya",
    address: "Ruko Pondok Jaya Blok B No. 5, Pondok Jaya, Tangerang Selatan",
    centerType: "Bahasa Inggris",
    courseTypes: ["Bahasa Inggris"],
    ageGroups: ["Kids", "Tween", "Teen"],
    priceMin: 400000,
    priceMax: 800000,
    rating: 4.8,
    reviews: 35,
    ageRange: "4 – 15 tahun",
    hours: "Sen–Sab 10:00–20:00",
    description: "Pusat kursus bahasa Inggris dengan metode komunikatif yang menyenangkan. Program tersedia untuk berbagai level dari beginner hingga advanced.",
    phone: "0817-6789-0124",
    tag: "Popular",
    icon: "💬",
    photo: PH("english-class-students"),
    photos: [PH("english-conversation"), PH("kids-speaking-english")],
    reviewsList: [
      { name: "Budi S.", rating: 5, comment: "Metode belajarnya seru, anak saya jadi tidak takut berbicara bahasa Inggris!", date: "Mar 2025" },
      { name: "Rina A.", rating: 5, comment: "Gurunya native, cara mengajarnya sangat efektif untuk anak-anak.", date: "Feb 2025" },
    ],
  },
  {
    id: "lc2",
    category: "learning-center",
    name: "Kumon Bintaro Sektor 7",
    area: "Bintaro Sektor 7",
    address: "Ruko Bintaro Sektor 7 Blok A No. 12, Tangerang Selatan",
    centerType: "Matematika",
    courseTypes: ["Matematika"],
    ageGroups: ["Toddler", "Kids", "Tween", "Teen"],
    priceMin: 300000,
    priceMax: 500000,
    rating: 4.6,
    reviews: 48,
    ageRange: "3 – 16 tahun",
    hours: "Sel, Kam, Sab 14:00–18:00",
    description: "Program belajar mandiri Kumon untuk matematika dan membaca. Metode terbukti secara global membantu anak maju sesuai kemampuan masing-masing.",
    phone: "0818-7890-1235",
    icon: "📐",
    photo: PH("math-kids-learning"),
    photos: [PH("kumon-worksheets"), PH("kids-math-study")],
    reviewsList: [
      { name: "Siti R.", rating: 5, comment: "Anak saya naik 2 level dalam 3 bulan. Metode Kumon memang terbukti!", date: "Mar 2025" },
      { name: "Ahmad F.", rating: 4, comment: "Bagus untuk membangun kebiasaan belajar mandiri. Sabar dengan progress anak.", date: "Jan 2025" },
    ],
  },
  {
    id: "lc3",
    category: "learning-center",
    isFeatured: true,
    name: "Little Picasso Art Studio",
    area: "Bintaro Sektor 3",
    address: "Jl. Sektor 3 Bintaro No. 8, Tangerang Selatan",
    centerType: "Seni",
    courseTypes: ["Seni"],
    ageGroups: ["Toddler", "Kids", "Tween"],
    priceMin: 350000,
    priceMax: 600000,
    rating: 4.9,
    reviews: 29,
    ageRange: "3 – 12 tahun",
    hours: "Sen–Sab 09:00–18:00",
    description: "Studio seni kreatif dengan berbagai program: melukis, menggambar, keramik, dan mixed media. Guru berpengalaman dalam suasana studio yang nyaman.",
    phone: "0819-8901-2346",
    tag: "Top Rated",
    icon: "🎨",
    photo: PH("art-studio-kids"),
    photos: [PH("kids-painting"), PH("art-class-ceramics")],
    reviewsList: [
      { name: "Maya H.", rating: 5, comment: "Studio-nya keren banget! Anak saya langsung jatuh cinta sama seni sejak belajar di sini.", date: "Feb 2025" },
      { name: "Dewi K.", rating: 5, comment: "Guru-nya sabar dan kreatif. Karya anak saya sudah dipajang di rumah semua!", date: "Jan 2025" },
    ],
  },
  {
    id: "lc4",
    category: "learning-center",
    name: "MusicBox Studio",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 No. 30, Bintaro, Tangerang Selatan",
    centerType: "Musik",
    courseTypes: ["Musik"],
    ageGroups: ["Kids", "Tween", "Teen"],
    priceMin: 500000,
    priceMax: 900000,
    rating: 4.7,
    reviews: 33,
    ageRange: "4 – 17 tahun",
    hours: "Sen–Sab 10:00–19:00",
    description: "Sekolah musik dengan instruktur profesional. Tersedia kelas piano, gitar, drum, vokal, dan biola untuk semua level dari pemula hingga mahir.",
    phone: "0820-9012-3457",
    icon: "🎵",
    photo: PH("music-school-piano"),
    photos: [PH("kids-guitar-lesson"), PH("music-performance")],
    reviewsList: [
      { name: "Hendra W.", rating: 5, comment: "Instruktur profesional dan sabar. Anak saya sudah bisa main piano dalam 2 bulan!", date: "Mar 2025" },
      { name: "Fitri L.", rating: 4, comment: "Pilihan instrumen lengkap. Jadwal fleksibel, cocok untuk anak sekolah.", date: "Feb 2025" },
    ],
  },
  {
    id: "lc5",
    category: "learning-center",
    name: "Code For Kids Bintaro",
    area: "BSD City",
    address: "Jl. BSD Raya No. 55, BSD City, Tangerang Selatan",
    centerType: "Coding/Robotik",
    courseTypes: ["Coding/Robotik"],
    ageGroups: ["Kids", "Tween", "Teen"],
    priceMin: 600000,
    priceMax: 1000000,
    rating: 4.8,
    reviews: 21,
    ageRange: "6 – 16 tahun",
    hours: "Sab–Min 09:00–17:00",
    description: "Kelas coding dan robotika untuk anak. Program Scratch, Python, dan Arduino untuk mengembangkan kemampuan berpikir logis dan kreativitas digital.",
    phone: "0821-0123-4568",
    tag: "New",
    icon: "💻",
    photo: PH("coding-kids-computer"),
    photos: [PH("kids-robotics"), PH("coding-class")],
    reviewsList: [
      { name: "Agus P.", rating: 5, comment: "Anak saya umur 8 tahun sudah bisa bikin game sendiri! Instrukturnya sabar banget.", date: "Mar 2025" },
      { name: "Budi S.", rating: 5, comment: "Kurikulum coding-nya terstruktur. Anak jadi terbiasa berpikir logis.", date: "Jan 2025" },
    ],
  },
  {
    id: "lc6",
    category: "learning-center",
    name: "FlipKids Gymnastics Center",
    area: "Bintaro Sektor 7",
    address: "Ruko Bintaro Sektor 7 Blok C No. 3, Tangerang Selatan",
    centerType: "Gimnastik",
    courseTypes: ["Gimnastik"],
    ageGroups: ["Toddler", "Kids", "Tween"],
    priceMin: 450000,
    priceMax: 750000,
    rating: 4.6,
    reviews: 18,
    ageRange: "3 – 14 tahun",
    hours: "Sab–Min 09:00–16:00",
    description: "Pusat senam dan gimnastik anak dengan peralatan berstandar keamanan internasional. Program dari senam dasar untuk balita hingga akrobatik dan cheerleading untuk anak yang lebih besar.",
    phone: "0822-1234-5679",
    icon: "🤸",
    photo: PH("gymnastics-kids-center"),
    photos: [PH("kids-gymnastics"), PH("gymnastics-training")],
    reviewsList: [
      { name: "Rina A.", rating: 5, comment: "Peralatan aman dan instrukturnya sangat sabar. Anak saya jadi jauh lebih lincah dan percaya diri!", date: "Feb 2025" },
      { name: "Siti R.", rating: 4, comment: "Kelas senam balitanya seru banget. Anak kami yang 3 tahun pun langsung suka.", date: "Jan 2025" },
    ],
  },
  {
    id: "lc7",
    category: "learning-center",
    name: "RhythmKids Dance Studio",
    area: "Bintaro Sektor 7",
    address: "Ruko Sektor 7 Blok D No. 9, Bintaro, Tangerang Selatan",
    centerType: "Tari & Balet",
    courseTypes: ["Tari & Balet"],
    ageGroups: ["Toddler", "Kids", "Tween"],
    priceMin: 350000,
    priceMax: 650000,
    rating: 4.8,
    reviews: 24,
    ageRange: "3 – 15 tahun",
    hours: "Sen–Sab 10:00–19:00",
    description: "Studio tari anak dengan kelas hip-hop, jazz, dan kontemporer. Dipandu instruktur berpengalaman dalam suasana yang menyenangkan dan penuh semangat.",
    phone: "0823-1122-3344",
    tag: "New",
    icon: "💃",
    photo: PH("dance-kids-studio"),
    photos: [PH("kids-dancing"), PH("dance-performance-kids")],
    reviewsList: [
      { name: "Dian M.", rating: 5, comment: "Instruktur sabar dan kreatif. Anak saya jadi lebih percaya diri tampil di depan umum.", date: "Mar 2025" },
      { name: "Rina A.", rating: 5, comment: "Kelasnya seru banget! Anak kami selalu excited tiap mau latihan.", date: "Feb 2025" },
    ],
  },
  {
    id: "lc8",
    category: "learning-center",
    name: "Prima Ballet Academy",
    area: "BSD City",
    address: "Jl. BSD Raya Utama No. 12, BSD City, Tangerang Selatan",
    centerType: "Tari & Balet",
    courseTypes: ["Tari & Balet"],
    ageGroups: ["Toddler", "Kids", "Tween"],
    priceMin: 500000,
    priceMax: 900000,
    rating: 4.9,
    reviews: 19,
    ageRange: "3 – 14 tahun",
    hours: "Sen–Sab 09:00–18:00",
    description: "Akademi balet anak dengan metode Royal Academy of Dance (RAD). Program terstruktur dari level dasar hingga persiapan ujian balet internasional.",
    phone: "0824-2233-4455",
    icon: "🩰",
    photo: PH("ballet-kids-class"),
    photos: [PH("ballet-performance"), PH("ballet-studio")],
    reviewsList: [
      { name: "Maya H.", rating: 5, comment: "Metode RAD yang digunakan sangat terstruktur. Anak saya progresnya luar biasa!", date: "Mar 2025" },
      { name: "Fitri L.", rating: 5, comment: "Studio bersih dan instruktur profesional. Anak kami sudah lulus ujian balet grade 1.", date: "Jan 2025" },
    ],
  },
  {
    id: "lc9",
    category: "learning-center",
    name: "Kreasi Seni Studio BSD",
    area: "BSD City",
    address: "Ruko BSD City Blok A No. 18, BSD City, Tangerang Selatan",
    centerType: "Seni",
    courseTypes: ["Seni"],
    ageGroups: ["Kids", "Tween", "Teen"],
    priceMin: 400000,
    priceMax: 750000,
    rating: 4.6,
    reviews: 15,
    ageRange: "5 – 17 tahun",
    hours: "Sen–Sab 10:00–18:00",
    description: "Studio seni ekspresif di BSD dengan program melukis, ilustrasi digital, dan kerajinan tangan. Mengembangkan kreativitas anak dengan pendekatan seni kontemporer yang menyenangkan.",
    phone: "0825-3344-5566",
    icon: "🎨",
    photo: PH("art-studio-bsd"),
    photos: [PH("kids-painting-bsd"), PH("art-craft-class")],
    reviewsList: [
      { name: "Dewi K.", rating: 5, comment: "Instrukturnya kreatif dan sabar. Anak saya sekarang hobi menggambar setiap hari!", date: "Feb 2025" },
      { name: "Siti R.", rating: 4, comment: "Kelas ilustrasi digitalnya seru banget. Anak saya jadi tertarik berkarir di bidang desain.", date: "Jan 2025" },
    ],
  },
  {
    id: "lc10",
    category: "learning-center",
    name: "Global English Academy BSD",
    area: "BSD City",
    address: "Ruko BSD Utama Blok B No. 25, BSD City, Tangerang Selatan",
    centerType: "Bahasa Inggris",
    courseTypes: ["Bahasa Inggris"],
    ageGroups: ["Kids", "Tween", "Teen"],
    priceMin: 450000,
    priceMax: 800000,
    rating: 4.7,
    reviews: 31,
    ageRange: "5 – 17 tahun",
    hours: "Sen–Sab 13:00–20:00",
    description: "Lembaga kursus bahasa Inggris di BSD dengan program IELTS, TOEFL, dan conversational English. Instruktur bersertifikat internasional dengan metode immersive yang terbukti efektif.",
    phone: "0826-4455-6677",
    tag: "Popular",
    icon: "💬",
    photo: PH("english-academy-bsd"),
    photos: [PH("english-class-bsd"), PH("ielts-preparation")],
    reviewsList: [
      { name: "Ahmad F.", rating: 5, comment: "Program IELTS-nya sangat terstruktur. Anak saya naik band score 1.5 dalam 3 bulan!", date: "Mar 2025" },
      { name: "Budi S.", rating: 5, comment: "Instruktur berpengalaman dan metodenya fun. Anak jadi tidak malu berbicara bahasa Inggris.", date: "Feb 2025" },
    ],
  },

  {
    id: "lc11",
    category: "learning-center",
    name: "BrainSpark Robotics Jr.",
    area: "Bintaro Sektor 1",
    address: "Jl. Bintaro Raya No. 17, Bintaro Sektor 1, Tangerang Selatan",
    centerType: "Coding/Robotik",
    courseTypes: ["Coding/Robotik"],
    ageGroups: ["Kids", "Tween"],
    priceMin: 150000,
    priceMax: 180000,
    rating: 4.5,
    reviews: 12,
    ageRange: "6 – 13 tahun",
    hours: "Sab–Min 09:00–14:00",
    description: "Kelas robotika dasar dengan biaya terjangkau. Anak-anak belajar merakit robot sederhana dan memahami konsep mekanik dasar menggunakan kit LEGO Technic yang aman.",
    phone: "0811-2233-4456",
    tag: "Budget Pick",
    icon: "🤖",
    photo: PH("robotics-junior-class"),
    photos: [PH("kids-lego-robotics"), PH("robotics-assembly")],
    reviewsList: [
      { name: "Hendra W.", rating: 5, comment: "Harganya sangat terjangkau tapi kualitas pengajarnya bagus. Anak saya langsung suka robotik!", date: "Mar 2025" },
      { name: "Agus P.", rating: 4, comment: "Program pengenalan robotik yang solid. Cocok untuk memulai sebelum masuk kelas lanjutan.", date: "Feb 2025" },
    ],
  },
  {
    id: "lc12",
    category: "learning-center",
    name: "Elite Music Conservatory",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Blok A No. 5, Bintaro, Tangerang Selatan",
    centerType: "Musik",
    courseTypes: ["Musik"],
    ageGroups: ["Kids", "Tween", "Teen"],
    priceMin: 1500000,
    priceMax: 2000000,
    rating: 4.9,
    reviews: 16,
    ageRange: "5 – 18 tahun",
    hours: "Sen–Sab 10:00–20:00",
    description: "Konservatori musik premium dengan instruktur lulusan luar negeri. Program intensif piano klasik, biola, dan vokal opera. Persiapan ujian ABRSM dan Trinity College London.",
    phone: "0812-3456-7891",
    tag: "Premium",
    icon: "🎹",
    photo: PH("music-conservatory"),
    photos: [PH("piano-lesson-premium"), PH("violin-class-elite")],
    reviewsList: [
      { name: "Maya H.", rating: 5, comment: "Instrukturnya luar biasa, punya gelar dari Vienna. Investasi terbaik untuk bakat musik anak.", date: "Mar 2025" },
      { name: "Dewi K.", rating: 5, comment: "Anak saya lulus ABRSM Grade 5 dalam setahun. Standar pengajaran kelas dunia.", date: "Jan 2025" },
    ],
  },
  {
    id: "lc13",
    category: "learning-center",
    name: "Cambridge Junior Prep",
    area: "BSD City",
    address: "Jl. BSD Raya Utama No. 88, BSD City, Tangerang Selatan",
    centerType: "Bahasa Inggris",
    courseTypes: ["Bahasa Inggris"],
    ageGroups: ["Kids", "Tween", "Teen"],
    priceMin: 2500000,
    priceMax: 3500000,
    rating: 4.8,
    reviews: 9,
    ageRange: "6 – 16 tahun",
    hours: "Sen–Jum 14:00–18:00",
    description: "Program persiapan Cambridge Young Learners dan Cambridge IGCSE intensif. Native English teacher dari UK, rasio kelas 1:5, modul eksklusif dan laporan perkembangan mingguan.",
    phone: "0813-4567-8902",
    tag: "Premium",
    icon: "🎓",
    photo: PH("cambridge-prep-class"),
    photos: [PH("cambridge-exam-prep"), PH("native-teacher-class")],
    reviewsList: [
      { name: "Fitri L.", rating: 5, comment: "Anak saya lulus Cambridge YLE Movers dengan distinction! Gurunya native speaker yang sangat profesional.", date: "Mar 2025" },
      { name: "Ahmad F.", rating: 5, comment: "Harga premium tapi worth it. Metode pengajaran Cambridge-nya benar-benar membuat anak fasih.", date: "Feb 2025" },
    ],
  },

  // ── DAYCARES ─────────────────────────────────────────────
  {
    id: "d1",
    category: "daycare",
    name: "Happy Tots Daycare",
    area: "Bintaro Sektor 3",
    address: "Jl. Sektor 3 No. 12, Bintaro, Tangerang Selatan",
    priceMin: 1500000,
    priceMax: 2500000,
    careHours: "full-day",
    daycareFeatures: ["CCTV", "Meals", "WhatsApp Report"],
    daycareAgeGroups: ["Bayi (0–1 thn)", "Toddler (1–2 thn)", "Balita (2–4 thn)", "Usia 4+ thn"],
    rating: 4.7,
    reviews: 28,
    ageRange: "6 bulan – 5 tahun",
    hours: "06:30 – 18:00",
    description: "Penitipan anak yang nyaman dan aman dengan pengasuh berpengalaman. Program stimulasi perkembangan dan laporan harian dikirim ke orang tua via WhatsApp.",
    phone: "0823-2345-6780",
    tag: "Most Loved",
    icon: "🧸",
    photo: PH("daycare-toddlers"),
    photos: [PH("daycare-play-area"), PH("babies-nursery")],
    reviewsList: [
      { name: "Maya H.", rating: 5, comment: "Pengasuhnya sangat care, laporan harian via WA bikin orang tua tenang bekerja.", date: "Mar 2025" },
      { name: "Dewi K.", rating: 5, comment: "Tempat bersih, anak happy, pengasuh berpengalaman. Sangat rekomendasikan!", date: "Feb 2025" },
    ],
  },
  {
    id: "d2",
    category: "daycare",
    isFeatured: true,
    name: "Sunshine Nursery",
    area: "Bintaro Sektor 7",
    address: "Jl. Bintaro Utama VII No. 8, Sektor 7, Tangerang Selatan",
    priceMin: 2000000,
    priceMax: 3000000,
    careHours: "full-day",
    daycareFeatures: ["CCTV", "Meals", "CCTV Live Streaming", "WhatsApp Report"],
    daycareAgeGroups: ["Bayi (0–1 thn)", "Toddler (1–2 thn)", "Balita (2–4 thn)"],
    rating: 4.8,
    reviews: 19,
    ageRange: "3 bulan – 4 tahun",
    hours: "07:00 – 17:00",
    description: "Nursery premium dengan CCTV 24 jam, area bermain indoor, dan program stimulasi bayi. Rasio pengasuh 1:3 memastikan perhatian penuh untuk setiap anak.",
    phone: "0824-3456-7891",
    tag: "Premium",
    icon: "🧸",
    photo: PH("nursery-babies-bright"),
    photos: [PH("nursery-crib-room"), PH("baby-play-mat")],
    reviewsList: [
      { name: "Fitri L.", rating: 5, comment: "Premium dan terpercaya. CCTV bisa dipantau real-time dari HP. Sangat aman!", date: "Mar 2025" },
      { name: "Ahmad F.", rating: 5, comment: "Rasio pengasuh 1:3 beneran terjaga. Bayi kami diperhatikan dengan sangat baik.", date: "Jan 2025" },
    ],
  },
  {
    id: "d3",
    category: "daycare",
    name: "Little Angels Daycare",
    area: "Pondok Aren",
    address: "Jl. Pondok Aren Raya No. 45, Pondok Aren, Tangerang Selatan",
    priceMin: 1000000,
    priceMax: 1800000,
    careHours: "full-day",
    daycareFeatures: ["Meals", "WhatsApp Report"],
    daycareAgeGroups: ["Toddler (1–2 thn)", "Balita (2–4 thn)", "Usia 4+ thn"],
    rating: 4.5,
    reviews: 34,
    ageRange: "1 – 5 tahun",
    hours: "06:00 – 18:00",
    description: "Daycare terjangkau dengan suasana rumahan yang hangat. Pengasuh bersertifikat dengan program kegiatan harian terstruktur dan menu makan siang bergizi.",
    phone: "0825-4567-8902",
    tag: "Budget Friendly",
    icon: "🧸",
    photo: PH("daycare-home-cozy"),
    photos: [PH("daycare-lunch-time"), PH("toddler-activities")],
    reviewsList: [
      { name: "Agus P.", rating: 5, comment: "Harga bersahabat tapi kualitas tidak murahan. Menu makan siangnya juga bergizi.", date: "Feb 2025" },
      { name: "Budi S.", rating: 4, comment: "Suasana rumahan bikin anak betah. Pengasuhnya sayang sama anak-anak.", date: "Jan 2025" },
    ],
  },

  // ── PLAYGROUNDS ──────────────────────────────────────────
  {
    id: "pg1",
    category: "playground",
    name: "Kidzooona Bintaro Xchange",
    area: "Bintaro Sektor 7",
    address: "Bintaro Xchange Mall Lt. 3, Jl. Bintaro Sektor 7, Tangerang Selatan",
    playgroundType: "indoor",
    isFree: false,
    priceMin: 50000,
    priceMax: 100000,
    rating: 4.6,
    reviews: 87,
    ageRange: "1 – 10 tahun",
    hours: "10:00 – 21:00",
    description: "Wahana bermain indoor terlengkap di Bintaro. Trampolin, mandi bola, wahana edukatif, dan area bermain bebas. Tiket harian & paket bulanan tersedia.",
    phone: "0826-5678-9013",
    tag: "Popular",
    icon: "🎡",
    photo: PH("indoor-playground-colorful"),
    photos: [PH("kids-trampoline"), PH("ball-pit-kids")],
    reviewsList: [
      { name: "Rina A.", rating: 5, comment: "Anak-anak SUKA banget! Bisa main seharian. Harga tiket sepadan dengan fasilitasnya.", date: "Mar 2025" },
      { name: "Siti R.", rating: 4, comment: "Tempat bermain terlengkap di Bintaro. Aman dan bersih, pengawas juga banyak.", date: "Feb 2025" },
    ],
    tangselKidsRating: {
      cleanliness: 5, value: 3, safety: 5, fun: 5, facilities: 5,
      verdict: "Pilihan terbaik untuk anak aktif di Bintaro. Wahana lengkap dan pengawasan ketat dari staf yang terlatih. Harga sedikit di atas rata-rata tapi benar-benar sepadan dengan fasilitasnya.",
    },
  },
  {
    id: "pg2",
    category: "playground",
    name: "Timezone Bintaro",
    area: "Bintaro Jaya Xchange",
    address: "Bintaro Jaya Xchange, Jl. Jombang Raya, Tangerang Selatan",
    playgroundType: "indoor",
    isFree: false,
    priceMin: 100000,
    priceMax: 150000,
    rating: 4.4,
    reviews: 63,
    ageRange: "5 – 15 tahun",
    hours: "10:00 – 22:00",
    description: "Pusat hiburan keluarga dengan ratusan mesin arcade, area anak, dan redemption center. Cocok untuk pesta ulang tahun dan gathering keluarga.",
    phone: "0827-6789-0124",
    icon: "🎮",
    photo: PH("arcade-game-center"),
    photos: [PH("arcade-machines"), PH("kids-arcade-fun")],
    reviewsList: [
      { name: "Hendra W.", rating: 4, comment: "Anak kami betah berjam-jam di sini. Koleksi game-nya selalu diupdate.", date: "Feb 2025" },
      { name: "Maya H.", rating: 4, comment: "Seru buat anak yang sudah besar. Sistem reward-nya bikin anak semangat.", date: "Jan 2025" },
    ],
    tangselKidsRating: {
      cleanliness: 4, value: 3, safety: 4, fun: 5, facilities: 4,
      verdict: "Surga buat anak yang suka game arcade. Lebih cocok untuk usia 6 ke atas. Token bisa habis cepat — tetapkan budget sebelum masuk agar tidak melebihi pengeluaran.",
    },
  },
  {
    id: "pg3",
    category: "playground",
    name: "Taman Jajan BSD",
    area: "BSD City",
    address: "Jl. BSD Raya No. 1, BSD City, Tangerang Selatan",
    playgroundType: "outdoor",
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    rating: 4.3,
    reviews: 45,
    ageRange: "Semua usia",
    hours: "Buka 24 jam",
    description: "Taman publik dengan area bermain anak, jogging track, dan food truck. Tempat nongkrong keluarga yang nyaman dan gratis di jantung BSD.",
    phone: "-",
    tag: "Gratis",
    icon: "🌳",
    photo: PH("outdoor-park-green"),
    photos: [PH("park-playground-outdoor"), PH("family-park-weekend")],
    reviewsList: [
      { name: "Fitri L.", rating: 4, comment: "Gratis dan nyaman! Sering bawa anak ke sini tiap weekend. Food truck-nya enak-enak juga.", date: "Mar 2025" },
      { name: "Agus P.", rating: 4, comment: "Taman yang terawat, cocok buat olahraga pagi sambil bawa anak bermain.", date: "Feb 2025" },
    ],
    tangselKidsRating: {
      cleanliness: 3, value: 5, safety: 3, fun: 4, facilities: 3,
      verdict: "Taman gratis yang cukup terawat di tengah BSD. Cocok untuk bersantai sore bersama keluarga, meski fasilitas bermain anak masih terbatas. Datang pagi untuk suasana terbaik.",
    },
  },
  {
    id: "pg4",
    category: "playground",
    name: "Lapangan Bintaro Jaya",
    area: "Bintaro",
    address: "Jl. Bintaro Raya No. 1, Bintaro, Tangerang Selatan",
    playgroundType: "outdoor",
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    rating: 4.2,
    reviews: 32,
    ageRange: "Semua usia",
    hours: "05:00 – 21:00",
    description: "Lapangan olahraga dan taman bermain outdoor gratis. Tersedia lapangan futsal, area bermain anak, dan jalur sepeda di kawasan Bintaro.",
    phone: "-",
    tag: "Gratis",
    icon: "⚽",
    photo: PH("outdoor-sports-field"),
    photos: [PH("futsal-field"), PH("kids-bicycle-park")],
    reviewsList: [
      { name: "Budi S.", rating: 4, comment: "Lapangan futsal-nya bagus, anak-anak bisa main bebas di sini tiap sore.", date: "Feb 2025" },
      { name: "Rina A.", rating: 4, comment: "Area bermain anak tersedia dan aman. Gratis lagi, cocok buat aktivitas harian.", date: "Jan 2025" },
    ],
    tangselKidsRating: {
      cleanliness: 3, value: 5, safety: 3, fun: 4, facilities: 2,
      verdict: "Pilihan gratis yang oke untuk olahraga keluarga di Bintaro. Area bermain anak ada tapi minim. Sangat cocok untuk anak yang sudah bisa bersepeda atau bermain futsal.",
    },
  },

  {
    id: "pg5",
    category: "playground",
    name: "Taman Bermain Griya Loka BSD",
    area: "BSD City",
    address: "Perumahan Griya Loka, BSD City, Tangerang Selatan",
    playgroundType: "outdoor",
    isFree: false,
    priceMin: 15000,
    priceMax: 25000,
    rating: 4.1,
    reviews: 27,
    ageRange: "2 – 10 tahun",
    hours: "07:00 – 18:00",
    description: "Area bermain outdoor terjangkau di dalam kawasan perumahan Griya Loka BSD. Dilengkapi wahana perosotan, ayunan, dan jungkat-jungkit. Ideal untuk anak usia dini yang ingin bermain di luar ruangan.",
    phone: "-",
    tag: "Murah Meriah",
    icon: "🎡",
    photo: PH("outdoor-playground-budget"),
    photos: [PH("kids-slide-outdoor"), PH("playground-swing-kids")],
    reviewsList: [
      { name: "Sari N.", rating: 4, comment: "Murah dan dekat dari rumah. Anak-anak senang main perosotan dan ayunan setiap sore.", date: "Feb 2025" },
      { name: "Dodi R.", rating: 4, comment: "Harga terjangkau, cocok untuk main santai. Tempatnya bersih dan terawat.", date: "Jan 2025" },
    ],
    tangselKidsRating: {
      cleanliness: 4, value: 5, safety: 3, fun: 3, facilities: 2,
      verdict: "Pilihan hemat untuk bermain outdoor di BSD. Fasilitas sederhana tapi cukup untuk anak-anak yang aktif. Sangat worth it untuk harganya.",
    },
  },
  {
    id: "pg6",
    category: "playground",
    isFeatured: true,
    name: "Amazonia Indoor Play BSD",
    area: "BSD City",
    address: "Jl. Pahlawan Seribu No. 10, BSD City, Tangerang Selatan",
    playgroundType: "indoor",
    isFree: false,
    priceMin: 250000,
    priceMax: 350000,
    rating: 4.8,
    reviews: 44,
    ageRange: "1 – 12 tahun",
    hours: "Sen–Min 10:00–21:00",
    description: "Playground indoor premium terbesar di BSD dengan zona bermain multi-lantai, kolam bola, climbing wall, mini roller coaster, dan area khusus bayi. Fasilitas kelas dunia untuk pengalaman bermain tak terlupakan.",
    phone: "0812-8899-0011",
    tag: "Premium",
    icon: "🎡",
    photo: PH("premium-indoor-playground"),
    photos: [PH("indoor-play-premium"), PH("kids-climbing-wall")],
    reviewsList: [
      { name: "Citra M.", rating: 5, comment: "Playground premium terbaik di BSD! Anak saya tidak mau pulang. Wahana lengkap dan sangat aman.", date: "Mar 2025" },
      { name: "Fajar H.", rating: 5, comment: "Worth every rupiah. Fasilitas kelas dunia, staf ramah dan sigap. Anak kami betah berjam-jam.", date: "Feb 2025" },
    ],
    tangselKidsRating: {
      cleanliness: 5, value: 4, safety: 5, fun: 5, facilities: 5,
      verdict: "Playground premium terbaik di kawasan BSD. Harga memang tinggi tapi sebanding dengan fasilitas dan pengalaman yang ditawarkan. Cocok untuk acara ulang tahun atau hari spesial anak.",
    },
  },

  // ── CLINICS ──────────────────────────────────────────────
  {
    id: "cl1",
    isFeatured: true,
    category: "clinic",
    name: "Klinik Anak Sehat Bintaro",
    area: "Bintaro Sektor 7",
    address: "Jl. Bintaro Utama VII No. 28, Sektor 7, Tangerang Selatan",
    priceMin: 150000,
    priceMax: 350000,
    clinicServices: ["Terapi Wicara", "Sensori Integrasi (SI)"],
    bpjs: true,
    rating: 4.8,
    reviews: 64,
    ageRange: "0 – 18 tahun",
    hours: "Sen–Jum 08:00–20:00, Sab 08:00–16:00",
    description: "Klinik anak spesialis dengan dokter spesialis anak berpengalaman. Layanan imunisasi, tumbuh kembang, konsultasi gizi, dan unit gawat darurat tersedia.",
    phone: "0831-1234-5671",
    tag: "Top Rated",
    icon: "🏥",
    photo: PH("pediatric-doctor-kids"),
    photos: [PH("clinic-waiting-room"), PH("doctor-child-exam")],
    reviewsList: [
      { name: "Dewi K.", rating: 5, comment: "Dokternya sabar dan komunikatif. Antrian teratur dan tidak terlalu lama menunggu.", date: "Mar 2025" },
      { name: "Budi S.", rating: 5, comment: "Pelayanan sangat profesional. Anak saya jadi tidak takut ke dokter lagi!", date: "Feb 2025" },
    ],
  },
  {
    id: "cl2",
    category: "clinic",
    name: "RS Hermina Bintaro",
    area: "Bintaro Sektor 7",
    address: "Jl. Raden Fatah No. 25, Bintaro Sektor 7, Tangerang Selatan",
    priceMin: 200000,
    priceMax: 500000,
    clinicServices: ["Psikologi Anak", "Perilaku / ABA"],
    bpjs: true,
    rating: 4.6,
    reviews: 128,
    ageRange: "Semua usia",
    hours: "24 jam",
    description: "Rumah sakit ibu dan anak dengan fasilitas lengkap. Spesialis anak, kebidanan, dan NICU tersedia. Layanan emergency 24 jam dan ambulans.",
    phone: "021-7372525",
    tag: "24 Jam",
    icon: "🏥",
    photo: PH("hospital-modern"),
    photos: [PH("hospital-pediatric"), PH("hospital-emergency")],
    reviewsList: [
      { name: "Fitri L.", rating: 5, comment: "Fasilitas lengkap dan bersih. Dokter spesialis anak-nya sangat kompeten.", date: "Mar 2025" },
      { name: "Ahmad F.", rating: 4, comment: "IGD 24 jam sangat membantu saat anak demam tinggi tengah malam.", date: "Jan 2025" },
    ],
  },
  {
    id: "cl3",
    category: "clinic",
    name: "Pediatric Care BSD",
    area: "BSD City",
    address: "Ruko BSD Junction Blok A No. 8, BSD City, Tangerang Selatan",
    priceMin: 220000,
    priceMax: 400000,
    clinicServices: ["Terapi Okupasi", "Fisioterapi"],
    bpjs: false,
    rating: 4.7,
    reviews: 45,
    ageRange: "0 – 14 tahun",
    hours: "Sen–Sab 08:00–21:00",
    description: "Klinik pediatri modern dengan dokter spesialis anak yang berpengalaman. Layanan imunisasi, tumbuh kembang, dan konsultasi nutrisi anak tersedia.",
    phone: "0832-2345-6782",
    icon: "🏥",
    photo: PH("pediatric-clinic-modern"),
    photos: [PH("kids-doctor-check"), PH("clinic-interior")],
    reviewsList: [
      { name: "Rina A.", rating: 5, comment: "Klinik bersih dan nyaman. Dokternya teliti dan tidak terburu-buru.", date: "Feb 2025" },
      { name: "Siti R.", rating: 5, comment: "Pelayanan ramah, dokternya sangat penuh perhatian terhadap anak-anak.", date: "Jan 2025" },
    ],
  },

  {
    id: "cl4",
    category: "clinic",
    name: "Klinik Tumbuh Kembang Bintaro",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Raya No. 22, Bintaro, Tangerang Selatan",
    priceMin: 400000,
    priceMax: 600000,
    clinicServices: ["Terapi Wicara", "Terapi Okupasi", "Fisioterapi"],
    bpjs: false,
    rating: 4.8,
    reviews: 38,
    ageRange: "0 – 18 tahun",
    hours: "Sen–Jum 08:00–18:00, Sab 08:00–14:00",
    description: "Klinik tumbuh kembang anak spesialis dengan tim terapis multidisiplin. Layanan terapi wicara, terapi okupasi, dan fisioterapi dalam satu atap untuk kenyamanan keluarga.",
    phone: "0812-4455-6677",
    tag: "Spesialis",
    icon: "🏥",
    photo: PH("child-therapy-clinic"),
    photos: [PH("speech-therapy-kids"), PH("occupational-therapy")],
    reviewsList: [
      { name: "Laila S.", rating: 5, comment: "Terapis wicara-nya sabar dan profesional. Anak saya progresnya sangat baik setelah 3 bulan terapi.", date: "Mar 2025" },
      { name: "Rudi H.", rating: 5, comment: "Fasilitas lengkap, bisa satu pintu untuk berbagai jenis terapi. Sangat memudahkan orang tua.", date: "Feb 2025" },
    ],
  },
  {
    id: "cl5",
    category: "clinic",
    name: "Sentra Terapi Anak BSD",
    area: "BSD City",
    address: "Ruko BSD Utama Blok C No. 5, BSD City, Tangerang Selatan",
    priceMin: 650000,
    priceMax: 900000,
    clinicServices: ["Sensori Integrasi (SI)", "Perilaku / ABA", "Psikologi Anak"],
    bpjs: false,
    rating: 4.9,
    reviews: 22,
    ageRange: "0 – 12 tahun",
    hours: "Sen–Sab 08:00–17:00",
    description: "Pusat terapi anak premium dengan spesialisasi Sensori Integrasi, terapi ABA untuk anak dengan kebutuhan khusus, dan layanan psikologi anak. Tim psikolog dan terapis bersertifikat internasional.",
    phone: "0812-7766-5544",
    tag: "Premium",
    icon: "🏥",
    photo: PH("premium-therapy-center"),
    photos: [PH("sensory-integration-therapy"), PH("aba-therapy-kids")],
    reviewsList: [
      { name: "Vera N.", rating: 5, comment: "Terapi ABA-nya terstruktur dan efektif. Anak kami menunjukkan perkembangan signifikan dalam 6 bulan.", date: "Mar 2025" },
      { name: "Bram K.", rating: 5, comment: "Tim terapis sangat profesional dan berempati. Program SI-nya dirancang khusus sesuai kebutuhan anak.", date: "Jan 2025" },
    ],
  },

  // ── CAFES ────────────────────────────────────────────────
  {
    id: "cf1",
    category: "cafe",
    isFeatured: true,
    name: "Pik Nik Family Cafe",
    area: "Bintaro Sektor 3",
    address: "Jl. Sektor 3 No. 5, Bintaro, Tangerang Selatan",
    priceMin: 100000,
    priceMax: 200000,
    cafeFeatures: ["Playground Indoor", "Area Mewarnai", "Menu Khusus Anak", "AC"],
    priceCategory: "Normal",
    rating: 4.7,
    reviews: 52,
    ageRange: "Semua usia",
    hours: "Sen–Min 10:00–22:00",
    description: "Kafe ramah keluarga dengan area bermain anak indoor, menu khusus anak, dan sudut baca. Tempat nyaman untuk quality time bersama keluarga sambil menikmati kuliner lezat.",
    phone: "0833-3456-7893",
    tag: "Family Friendly",
    icon: "☕",
    photo: PH("family-cafe-cozy"),
    photos: [PH("cafe-kids-area"), PH("cafe-food-kids")],
    reviewsList: [
      { name: "Maya H.", rating: 5, comment: "Tempatnya cozy banget! Area bermain anak-nya didesain dengan aman. Makanannya juga enak.", date: "Mar 2025" },
      { name: "Dewi K.", rating: 5, comment: "Favorit kami sekeluarga! Anak-anak bisa main, orang tua bisa ngobrol santai.", date: "Feb 2025" },
    ],
  },
  {
    id: "cf2",
    category: "cafe",
    name: "Kids & Co. Cafe",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 No. 15, Bintaro, Tangerang Selatan",
    priceMin: 80000,
    priceMax: 180000,
    cafeFeatures: ["Area Mewarnai", "Menu Khusus Anak", "Kelas Memasak", "AC", "Wifi"],
    priceCategory: "Murah Sekali",
    rating: 4.5,
    reviews: 38,
    ageRange: "Semua usia",
    hours: "Sab–Min 09:00–21:00, Sen–Jum 13:00–21:00",
    description: "Kafe dengan konsep bermain dan belajar. Tersedia sewa mainan per jam, menu sehat untuk anak, dan kelas memasak anak setiap akhir pekan.",
    phone: "0834-4567-8904",
    icon: "☕",
    photo: PH("kids-cafe-play"),
    photos: [PH("cafe-kids-playing"), PH("children-cooking-class")],
    reviewsList: [
      { name: "Hendra W.", rating: 5, comment: "Kelas memasaknya seru banget! Anak kami sangat antusias dan pulang penuh kenangan.", date: "Feb 2025" },
      { name: "Fitri L.", rating: 4, comment: "Konsep unik dan edukatif. Anak-anak tidak hanya makan tapi juga belajar.", date: "Jan 2025" },
    ],
  },
  {
    id: "cf3",
    category: "cafe",
    name: "The Little Kitchen BSD",
    area: "BSD City",
    address: "Jl. BSD Raya Utama No. 20, BSD City, Tangerang Selatan",
    priceMin: 120000,
    priceMax: 250000,
    cafeFeatures: ["Playground Outdoor", "Area Mewarnai", "Menu Khusus Anak"],
    priceCategory: "Agak Mahal",
    rating: 4.8,
    reviews: 41,
    ageRange: "Semua usia",
    hours: "Sen–Min 10:00–22:00",
    description: "Restoran keluarga dengan taman bermain outdoor yang luas, area mewarnai, dan menu anak yang bergizi. Suasana garden cafe yang asri dan nyaman.",
    phone: "0835-5678-9015",
    tag: "Top Rated",
    icon: "☕",
    photo: PH("garden-cafe-kids"),
    photos: [PH("cafe-outdoor-garden"), PH("kids-menu-food")],
    reviewsList: [
      { name: "Agus P.", rating: 5, comment: "Taman bermainnya luas dan aman. Anak saya bisa main sepuasnya sementara kami makan.", date: "Mar 2025" },
      { name: "Budi S.", rating: 5, comment: "Suasana garden cafe-nya sangat nyaman. Menu anak-nya bervariasi dan bergizi.", date: "Feb 2025" },
    ],
  },

  {
    id: "cf4",
    category: "cafe",
    name: "Warung Makan Si Kecil",
    area: "Pondok Aren",
    address: "Jl. Pondok Aren Raya No. 12, Pondok Aren, Tangerang Selatan",
    priceMin: 30000,
    priceMax: 60000,
    cafeFeatures: ["Menu Khusus Anak"],
    priceCategory: "Murah",
    rating: 4.3,
    reviews: 29,
    ageRange: "Semua usia",
    hours: "Sen–Min 08:00–21:00",
    description: "Warung makan keluarga sederhana dengan menu rumahan yang lezat dan ramah di kantong. Menu anak tersedia dengan porsi sesuai usia dan bahan-bahan alami tanpa MSG.",
    phone: "0812-3344-9988",
    icon: "☕",
    photo: PH("family-warung-kids"),
    photos: [PH("kids-menu-warung"), PH("family-dining-simple")],
    reviewsList: [
      { name: "Wati S.", rating: 4, comment: "Murah meriah dan enak! Menu anak-anaknya bersih dan sehat. Cocok buat makan siang harian.", date: "Feb 2025" },
      { name: "Joko P.", rating: 4, comment: "Harga sangat terjangkau. Anak saya suka banget sama nasi telur dan sup sayurnya.", date: "Jan 2025" },
    ],
  },
  {
    id: "cf5",
    category: "cafe",
    name: "The Parenthood Bintaro",
    area: "Bintaro Sektor 7",
    address: "Jl. Bintaro Utama VII No. 99, Sektor 7, Tangerang Selatan",
    priceMin: 200000,
    priceMax: 400000,
    cafeFeatures: ["Playground Indoor", "Playground Outdoor", "Area Mewarnai", "Menu Khusus Anak", "Wifi", "AC"],
    priceCategory: "Mahal",
    rating: 4.9,
    reviews: 61,
    ageRange: "Semua usia",
    hours: "Sen–Min 10:00–22:00",
    description: "Restoran keluarga premium di Bintaro dengan konsep sophisticated yet family-friendly. Playground indoor dua lantai, private dining room, menu fine dining anak, dan barista specialty coffee untuk orang tua.",
    phone: "0812-1122-3344",
    tag: "Premium",
    icon: "☕",
    photo: PH("premium-family-restaurant"),
    photos: [PH("fine-dining-kids"), PH("premium-indoor-play")],
    reviewsList: [
      { name: "Karin W.", rating: 5, comment: "Worth every penny! Playground-nya luar biasa dan makanannya benar-benar fine dining quality. Date night dengan anak jadi mewah.", date: "Mar 2025" },
      { name: "Denny A.", rating: 5, comment: "Terbaik di Bintaro untuk family dining premium. Anak-anak happy, orang tua juga happy.", date: "Feb 2025" },
    ],
  },

  // ── MINI ZOO ─────────────────────────────────────────────
  {
    id: "mz1",
    category: "mini-zoo",
    isFeatured: true,
    name: "BioKids Tangsel",
    area: "Bintaro Sektor 7",
    address: "Jl. Bintaro Utama VII No. 50, Sektor 7, Tangerang Selatan",
    priceMin: 75000,
    priceMax: 100000,
    rating: 4.5,
    reviews: 76,
    ageRange: "2 – 12 tahun",
    hours: "Sab–Min 09:00–17:00, Sel–Jum 13:00–17:00",
    description: "Mini zoo edukatif dengan koleksi reptil, burung eksotis, kelinci, dan hewan peliharaan ramah anak. Tersedia feeding session dan edukasi satwa setiap hari.",
    phone: "0836-6789-0126",
    tag: "Edukatif",
    icon: "🦜",
    photo: PH("mini-zoo-kids"),
    photos: [PH("kids-petting-rabbits"), PH("reptile-exhibit-kids")],
    reviewsList: [
      { name: "Rina A.", rating: 5, comment: "Anak saya langsung jatuh cinta sama kelinci dan iguana! Feeding session-nya seru banget.", date: "Mar 2025" },
      { name: "Siti R.", rating: 4, comment: "Koleksi hewannya beragam dan terawat. Edukasi satwanya sangat informatif.", date: "Feb 2025" },
    ],
  },
  {
    id: "mz2",
    category: "mini-zoo",
    name: "Taman Satwa BSD",
    area: "BSD City",
    address: "Jl. BSD Raya No. 30, BSD City, Tangerang Selatan",
    priceMin: 50000,
    priceMax: 70000,
    rating: 4.3,
    reviews: 54,
    ageRange: "Semua usia",
    hours: "Sab–Min 08:00–18:00",
    description: "Taman satwa keluarga di BSD dengan koleksi ikan hias, burung, hewan ternak, dan area bermain. Cocok untuk pengenalan alam dan satwa sejak dini.",
    phone: "0837-7890-1237",
    icon: "🦜",
    photo: PH("petting-zoo-family"),
    photos: [PH("zoo-animals-kids"), PH("kids-feeding-animals")],
    reviewsList: [
      { name: "Ahmad F.", rating: 4, comment: "Harga terjangkau untuk pengalaman yang menyenangkan. Anak kami senang lihat sapi dan domba.", date: "Feb 2025" },
      { name: "Maya H.", rating: 4, comment: "Bagus untuk mengenalkan dunia hewan kepada anak. Staf-nya juga ramah.", date: "Jan 2025" },
    ],
  },

  {
    id: "mz3",
    category: "mini-zoo",
    name: "Pojok Satwa Gratis Bintaro",
    area: "Bintaro Sektor 3",
    address: "Taman Kota Bintaro Sektor 3, Tangerang Selatan",
    priceMin: 0,
    priceMax: 0,
    rating: 4.1,
    reviews: 38,
    ageRange: "Semua usia",
    hours: "Sab–Min 07:00–17:00",
    description: "Area pengenalan satwa gratis di taman kota Bintaro. Anak-anak dapat melihat dan berinteraksi dengan kelinci, marmut, dan burung dara dalam suasana taman terbuka yang menyenangkan.",
    phone: "-",
    tag: "Gratis",
    icon: "🦜",
    photo: PH("free-animal-corner"),
    photos: [PH("kids-petting-free"), PH("rabbits-park")],
    reviewsList: [
      { name: "Eko S.", rating: 4, comment: "Gratis dan anak-anak senang banget lihat kelinci! Cocok untuk jalan-jalan pagi akhir pekan.", date: "Feb 2025" },
      { name: "Nita R.", rating: 4, comment: "Tempat yang menyenangkan untuk mengenalkan anak pada hewan. Bonus: gratis!", date: "Jan 2025" },
    ],
  },
  {
    id: "mz4",
    category: "mini-zoo",
    name: "Kebun Binatang Mini Tangsel",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Raya No. 55, Bintaro, Tangerang Selatan",
    priceMin: 15000,
    priceMax: 25000,
    rating: 4.2,
    reviews: 31,
    ageRange: "2 – 12 tahun",
    hours: "Sab–Min 09:00–17:00",
    description: "Mini zoo terjangkau dengan koleksi hewan ternak dan unggas. Anak-anak bisa memberi makan ayam, bebek, kambing, dan kelinci dalam lingkungan yang aman dan menyenangkan.",
    phone: "0812-5566-7788",
    icon: "🐐",
    photo: PH("mini-farm-kids"),
    photos: [PH("kids-feeding-goats"), PH("farm-animals-kids")],
    reviewsList: [
      { name: "Tono W.", rating: 4, comment: "Harga sangat terjangkau untuk pengalaman langsung dengan hewan. Anak saya suka banget kasih makan kambing.", date: "Mar 2025" },
      { name: "Ayu L.", rating: 4, comment: "Murah meriah! Anak-anak senang sekali berinteraksi langsung dengan hewan ternaknya.", date: "Feb 2025" },
    ],
  },

  // ── SWIMMING POOLS ───────────────────────────────────────
  {
    id: "sw1",
    category: "swimming-pool",
    isFeatured: true,
    name: "Bintaro Sport Club",
    area: "Bintaro Sektor 7",
    address: "Jl. Bintaro Sektor 7 No. 5, Tangerang Selatan",
    priceMin: 50000,
    priceMax: 100000,
    poolFeatures: ["Kolam Anak", "Kelas Renang", "Loker", "Kantin"],
    rating: 4.6,
    reviews: 89,
    ageRange: "Semua usia",
    hours: "Sen–Min 06:00–21:00",
    description: "Kolam renang olimpik dengan kolam khusus anak berkedalaman 50 cm. Tersedia kelas renang anak dengan instruktur bersertifikat setiap hari.",
    phone: "0838-8901-2348",
    tag: "Kelas Renang",
    icon: "🏊",
    photo: PH("kids-swimming-pool"),
    photos: [PH("swimming-lesson-kids"), PH("pool-olympic")],
    reviewsList: [
      { name: "Hendra W.", rating: 5, comment: "Kolam anak-nya dangkal dan aman. Instruktur kelas renang sangat sabar mengajari anak kami.", date: "Mar 2025" },
      { name: "Dewi K.", rating: 4, comment: "Fasilitas lengkap, air selalu bersih dan jernih. Lokasi mudah dijangkau.", date: "Feb 2025" },
    ],
  },
  {
    id: "sw2",
    category: "swimming-pool",
    name: "Waterland BSD",
    area: "BSD City",
    address: "Jl. BSD Raya No. 45, BSD City, Tangerang Selatan",
    priceMin: 80000,
    priceMax: 150000,
    poolFeatures: ["Kolam Anak", "Seluncuran", "Kantin"],
    rating: 4.7,
    reviews: 112,
    ageRange: "3 tahun ke atas",
    hours: "Sab–Min 09:00–19:00",
    description: "Waterpark mini untuk keluarga dengan seluncuran, kolam arus, dan area bermain air. Pengalaman waterpark seru di Tangsel tanpa harus pergi jauh.",
    phone: "0839-9012-3459",
    tag: "Weekend Fun",
    icon: "🏊",
    photo: PH("waterpark-kids"),
    photos: [PH("water-slide-kids"), PH("kids-pool-splash")],
    reviewsList: [
      { name: "Fitri L.", rating: 5, comment: "Mini waterpark yang seru! Seluncurannya aman untuk anak dari usia 4 tahun ke atas.", date: "Mar 2025" },
      { name: "Agus P.", rating: 5, comment: "Alternatif lebih dekat dan terjangkau dari waterpark besar. Anak-anak betah seharian.", date: "Feb 2025" },
    ],
  },
  {
    id: "sw3",
    category: "swimming-pool",
    name: "Aqua Kids Bintaro",
    area: "Bintaro Sektor 9",
    address: "Jl. Sektor 9 Raya No. 18, Bintaro, Tangerang Selatan",
    priceMin: 40000,
    priceMax: 60000,
    poolFeatures: ["Kolam Anak", "Baby Swim", "Kelas Renang", "Indoor"],
    rating: 4.4,
    reviews: 67,
    ageRange: "1 – 12 tahun",
    hours: "Sen–Min 07:00–20:00",
    description: "Kolam renang khusus anak dengan air hangat dan fasilitas ramah keluarga. Tersedia kelas baby swim untuk bayi 6 bulan ke atas dan instruktur bersertifikat.",
    phone: "0840-0123-4560",
    icon: "🏊",
    photo: PH("baby-swimming-class"),
    photos: [PH("kids-pool-warm"), PH("swimming-class-toddler")],
    reviewsList: [
      { name: "Budi S.", rating: 4, comment: "Sangat cocok untuk bayi dan balita. Air kolam hangat jadi anak tidak kedinginan.", date: "Feb 2025" },
      { name: "Rina A.", rating: 5, comment: "Baby swim class-nya luar biasa! Bayi kami usia 8 bulan sudah berani di air.", date: "Jan 2025" },
    ],
  },
  {
    id: "sw4",
    category: "swimming-pool",
    name: "Kolam Renang Graha Raya",
    area: "Bintaro Sektor 1",
    address: "Komplek Graha Raya, Jl. Pahlawan Seribu, Tangerang Selatan",
    priceMin: 15000,
    priceMax: 20000,
    poolFeatures: ["Kolam Anak", "Loker"],
    rating: 4.1,
    reviews: 34,
    ageRange: "Semua usia",
    hours: "Sen–Min 06:00–18:00",
    description: "Kolam renang umum di kompleks perumahan Graha Raya dengan harga sangat terjangkau. Kolam anak berkedalaman 50 cm, cocok untuk pemula dan latihan renang sehari-hari.",
    phone: "0812-1122-3344",
    icon: "🏊",
    photo: PH("public-pool-kids"),
    photos: [PH("kids-swimming-pool"), PH("pool-outdoor")],
    reviewsList: [
      { name: "Yudi P.", rating: 4, comment: "Harga sangat murah untuk kolam yang cukup bersih. Anak kami rutin latihan renang di sini setiap weekend.", date: "Mar 2025" },
      { name: "Sari N.", rating: 4, comment: "Pilihan ekonomis untuk bawa anak berenang. Kolam anak dangkal dan aman.", date: "Feb 2025" },
    ],
  },

  // ── BOOKSTORES ───────────────────────────────────────────
  {
    id: "bk1",
    category: "bookstore",
    isFeatured: true,
    name: "Gramedia Bintaro Xchange",
    area: "Bintaro Sektor 7",
    address: "Bintaro Xchange Mall Lt. 1, Jl. Bintaro Sektor 7, Tangerang Selatan",
    priceMin: 0,
    priceMax: 0,
    bookCollection: ["Buku Indonesia", "Buku Inggris", "Stationery"],
    rating: 4.7,
    reviews: 93,
    ageRange: "Semua usia",
    hours: "Sen–Min 10:00–22:00",
    description: "Toko buku terlengkap di Bintaro dengan seksi anak yang luas. Koleksi buku anak bahasa Indonesia dan Inggris, alat tulis, mainan edukatif, dan area membaca gratis.",
    phone: "021-7452525",
    tag: "Terlengkap",
    icon: "📚",
    photo: PH("bookstore-kids-section"),
    photos: [PH("gramedia-books"), PH("kids-reading-books")],
    reviewsList: [
      { name: "Maya H.", rating: 5, comment: "Seksi buku anak-nya lengkap banget! Anak saya betah berjam-jam pilih buku di sini.", date: "Mar 2025" },
      { name: "Siti R.", rating: 5, comment: "Koleksi buku bilingual untuk anak sangat banyak. Staff-nya membantu rekomendasikan buku sesuai usia.", date: "Feb 2025" },
    ],
  },
  {
    id: "bk2",
    category: "bookstore",
    name: "Periplus BSD City",
    area: "BSD City",
    address: "Aeon Mall BSD City Lt. 1, Jl. BSD Raya, Tangerang Selatan",
    priceMin: 0,
    priceMax: 0,
    bookCollection: ["Buku Inggris", "Buku Import", "Stationery"],
    rating: 4.5,
    reviews: 47,
    ageRange: "Semua usia",
    hours: "Sen–Min 10:00–22:00",
    description: "Toko buku internasional dengan koleksi buku anak berbahasa Inggris terlengkap di Tangsel. Buku impor, mainan edukatif, dan stationery premium untuk anak.",
    phone: "021-5315959",
    icon: "📚",
    photo: PH("english-bookstore"),
    photos: [PH("books-kids-english"), PH("periplus-interior")],
    reviewsList: [
      { name: "Ahmad F.", rating: 5, comment: "Best English book collection in Tangsel for kids. My daughter loves browsing here!", date: "Feb 2025" },
      { name: "Dewi K.", rating: 4, comment: "Koleksi buku impor lengkap. Harga memang lebih mahal tapi worth it untuk kualitas.", date: "Jan 2025" },
    ],
  },
];

export const schools        = places.filter((p) => p.category === "school");
export const learningCenters = places.filter((p) => p.category === "learning-center");
export const daycares       = places.filter((p) => p.category === "daycare");
export const playgrounds    = places.filter((p) => p.category === "playground");
export const clinics        = places.filter((p) => p.category === "clinic");
export const cafes          = places.filter((p) => p.category === "cafe");
export const miniZoos       = places.filter((p) => p.category === "mini-zoo");
export const swimmingPools  = places.filter((p) => p.category === "swimming-pool");
export const bookstores     = places.filter((p) => p.category === "bookstore");
